from waftools.plugin import plugin

def plugin_configure(conf):
	if not conf.check_header("generic-nms.h"):
		return False
	return conf.check_library2("ncooler", uselib='nms')

configure, build = plugin('nms', configure=plugin_configure, needs_lib=True)
