from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_pkg('neuros-cooler-media', destvar='nms-media'):
        return False
    if not conf.check_pkg('neuros-cooler-core', destvar='nms-core'):
        return False
    return True

configure, build = plugin('nms', configure=plugin_configure, needs_lib=True, output_prio=1, extra_libs=['nms-core','nms-media','comnmsc'])
