from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_cfg(package="libxml-2.0", uselib_store="xml2", args="--cflags --libs"):
        return True
    return False

configure, build = plugin("rss", libs=["xml2"], configure=plugin_configure)
