def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_coreaudio'
  obj.source = 'coreaudio.c'
  obj.uselib = 'coreaudio glib-2.0'
  obj.includes = '../../include'

def configure(conf):
  conf.check_tool("checks")
  conf.check_header('AudioUnit/AudioUnit.h', define="HAVE_COREAUDIO")
  if conf.env['HAVE_COREAUDIO']:
    conf.env['LINKFLAGS_coreaudio'] = ['-framework CoreAudio',
                                       '-framework AudioUnit']
    conf.env['XMMS_PLUGINS_ENABLED'].append('coreaudio')
