from waflib import Errors
from waftools.plugin import plugin

def plugin_configure(conf):
    try:
        conf.check_cfg(package="mad", uselib_store="mad",
                args="--cflags --libs")
    except Errors.ConfigurationError:
        conf.check_cc(header_name="mad.h")
        conf.check_cc(lib="mad", uselib_store="mad")

configure, build = plugin('mad', configure=plugin_configure, libs=["mad"])
