from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_header("mad.h"):
        return False
    return conf.check_library2("mad", uselib='mad')

configure, build = plugin('mad', configure=plugin_configure,
                          source=['mad.c', 'xing.c', 'id3v1.c'],
                          needs_lib=True)
