def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_mad'
  obj.includes = '../../include'
  obj.source = ['mad.c', 'xing.c', 'id3v1.c']
  obj.uselib = 'mad glib-2.0'

def configure(conf):
  if conf.check_pkg('mad', destvar='mad'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('mad')
