#gtk2 client

Import('base_env')

xmms2_sources = Split ("playlist.c main.cpp xmmsplaylistwin.cpp xmmslistview.cpp")

env = base_env.Copy(CPPPATH = ['#src/clients//lib/xmmsclient', '#src', 
		'/usr/share/qt3/include',
		'#src/clients/lib/xmmsclient-qt'],
	LIBPATH = ["../lib/xmmsclient/", "../lib/xmmsclient-qt/"],
	LIBS = ["xmmsclient","xmmsclient-qt","qt"],
	tools=['default', 'qt'])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("dbus")

env.XmmsProgram("xmms2-qt", xmms2_sources)
