#gtk2 client

Import('base_env')

xmms2_sources = Split ("playlist.c main.cpp " +
		       "xmmsplaylistwin.cpp xmmslistview.cpp " +
		       "xmmstoolbar.cpp")

env = base_env.Copy(CPPPATH = ['#src/clients//lib/xmmsclient', '#src', 
		'#src/clients/lib/xmmsclient-qt', '/usr/include/qt3'],
	LIBPATH = ["../lib/xmmsclient/", "../lib/xmmsclient-qt/"],
	LIBS = ["xmmsclient","xmmsclient-qt"],
	tools=['default', 'qt'])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("dbus")
env.AddFlagsFromGroup("qt")

env.XmmsProgram("xmms2-qt", xmms2_sources)
