from waftools.plugin import plugin

def plugin_configure(conf):
	if not conf.check_cfg(path="sc68-config", package="sc68", uselib_store="sc68", atleast_version="2.3.0", args="--cflags --libs"):
		return False

	return True

configure, build = plugin('sc68', configure=plugin_configure,
                          source="sc68.c", libs=["sc68"])
