import os, Common
import Params

def build(bld):
    env = bld.env()

    obj = bld.create_obj('cc', 'program')
    obj.target = 'xmms2-et'
    obj.source = ['xmms2-et.c']
    obj.includes = '. ../../include'
    obj.uselib = 'glib2 socket resolv'
    obj.uselib_local = 'xmmsclient-glib xmmsclient'

    obj = bld.create_obj('subst')
    obj.source = 'xmms2-et-launcher.sh.in'
    obj.dict = {'PRG_PATH' : env['BINDIR']}
    Common.install_files('SCRIPTDIR', None, 'xmms2-et-launcher.sh', chmod=0755)

    obj = bld.create_obj('man')
    obj.files = ['xmms2-et.1']

def configure(conf):
    if Params.g_platform == 'sunos5':
        if not conf.check_library2("resolv", uselib='resolv'):
            return False
    elif Params.g_platform == 'win32':
        return False
    return True

def set_options(opt):
    pass
