def build(bld):
  obj = bld.create_obj('cc', 'program')
  obj.target = 'xmms2-et'
  obj.source = ['xmms2-et.c']
  obj.includes = '. ../../include'
  obj.uselib = 'glib-2.0'
  obj.uselib_local = 'xmmsclient-glib xmmsclient'

def configure(conf):
  return True

def set_options(opt):
  pass
