from waftools.plugin import plugin

def plugin_configure(conf):
    return conf.check_pkg('libpulse', destvar='libpulse')

configure, build = plugin('pulse', configure=plugin_configure,
                          source=['pulse.c', 'backend.c'],
                          extra_libs=['libpulse'], output_prio=5)
