from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="libpulse", args="--cflags --libs", uselib_store="pulse"):
        return False
    return True

configure, build = plugin("pulse", configure=plugin_configure,
                          source=["pulse.c", "backend.c"],
                          output_prio=25, libs=["pulse"])
