from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_cfg(package="alsa", uselib_store="alsa", args="--cflags --libs"):
        return True
    return False

configure, build = plugin("alsa", configure=plugin_configure,
                          libs=["alsa"], output_prio=40)
