import os
import Common
import Params

def build(bld):
  env = bld.env()

  obj = bld.create_obj('cc', 'program')
  obj.target = 'xmms2-mdns-dnssd'
  obj.source = ['mdns-dnssd.c']
  obj.includes = '. ../../../include'
  obj.uselib = 'glib2'
  if env['explicit_dnssd']:
    obj.uselib += ' dnssd'
  obj.uselib_local = 'xmmsclient-glib xmmsclient'

  obj = bld.create_obj('subst')
  obj.source = 'xmms2-mdns-launcher.sh.in'
  obj.dict = {'PRG_PATH' : env['BINDIR']}
  Common.install_files('SCRIPTDIR', None, 'xmms2-mdns-launcher.sh', chmod=0755)

def configure(conf):
  return False
  conf.env['explicit_dnssd'] = True

  if not conf.check_header('dns_sd.h'):
    return False
  if Params.g_platform == 'darwin':
    conf.env['explicit_dnssd'] = False
    return True
  else:
    return conf.check_library2('dns_sd', uselib='dnssd', mandatory=0)

  return True

def set_options(opt):
  pass
