import os
import Common

def build(bld):
  env = bld.env()

  obj = bld.create_obj('cc', 'program')
  obj.target = 'xmms2-mdns-avahi'
  obj.source = ['mdns-avahi.c']
  obj.includes = '. ../../../include'
  obj.uselib = 'glib2 avahiclient avahiglib'
  obj.uselib_local = 'xmmsclient-glib xmmsclient'

  obj = bld.create_obj('subst')
  obj.source = 'xmms2-mdns-launcher.sh.in'
  obj.dict = {'PRG_PATH' : env['BINDIR']}
  Common.install_files('SCRIPTDIR', None, 'xmms2-mdns-launcher.sh',chmod=0755)

  find = bld.create_obj('cc', 'program')
  find.target = 'xmms2-find-avahi'
  find.source = ['find-avahi.c']
  find.uselib = 'avahiclient'

  obj = bld.create_obj('man')
  obj.files = ['xmms2-mdns-avahi.1']

def configure(conf):
  return False
  return (conf.check_pkg('avahi-client', destvar='avahiclient') and
    conf.check_pkg('avahi-glib', destvar='avahiglib'))

def set_options(opt):
  pass
