# Plugin never tested! FEEDBACK PLEASE
from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.env["CXX"]:
        return False
    if not conf.check_cxx(header_name='mac/All.h'):
        return False
    if not conf.check_cc(lib="mac", uselib_store="mac"):
        return False
    return True

configure, build = plugin('mac', configure=plugin_configure,
                          source=['mac.cpp', 'source_adapter.cpp'],
                          libs=["mac"], tool="cxx")
