# Plugin never tested! FEEDBACK PLEASE
from xmmsenv.plugin import plugin

def plugin_configure(conf):
  conf.check_tool('g++')
  return conf.check_library2('mac', uselib='mac', mandatory=0)

configure, build = plugin('mac', configure=plugin_configure,
                          source=['mac.cpp', 'source_adapter.cpp'],
                          needs_lib=True, tool='cpp')
