language:
  - c

env:
  global:
    - secure: "YS7oBoXRQ9/PpiMOPFo0TftWozQo9gACzNZKdRMSt2i7L8pe8Zn46OVkjWDAsg1IhgdQjPHcmQ+XJriwRdihH17jSTVnxOSJW2L8KBR7ClNaMiRbiVCecudIub2uy++9C/b+9z+G6ag++7Xtn2j9T+rOTH7KVM2MQ29jTJrZ/M8="
    - secure: "lodjVMbITogvx6e+zwhwuFIIdxvVD4WIkvwbkp8ARw9qoDG+fCRe/CA/9wowjPhL/q02BYVkyZCPkkM3g722KHl9V2LSBBSBhIstSVRardXjbjZsnwX3vfL+bau04h2DkX28P35DoB+aeBrLqycqz6ToaKU/QSBk27ZfAJ2PTQo="

matrix:
  include:
    - env: BUILD_MODE=regular
      os: linux
      sudo: true
      dist: trusty
      compiler: gcc
    - env: BUILD_MODE=regular
      os: linux
      sudo: true
      dist: trusty
      compiler: clang
    - env: BUILD_MODE=regular
      os: osx
      osx_image: xcode7.2
      compiler: clang
    - env: BUILD_MODE=analysis
      os: linux
      sudo: true
      dist: trusty
      compiler: clang
    - env: BUILD_MODE=coverage
      os: linux
      sudo: true
      dist: trusty
      compiler: gcc

before_script:
  - utils/travis-build.sh install

script:
  - utils/travis-build.sh build

addons:
  apt:
    packages:
      - cython
      - doxygen
      - lcov
      - libao-dev
      - libasound2-dev
      #- libavahi-client-dev
      #- libavahi-glib-dev
      - libavcodec-dev
      - libboost-dev
      - libboost-signals-dev
      #- libcdio-cdda-dev
      - libcunit1-dev
      - libcurl4-gnutls-dev
      #- libdiscid0-dev
      - libecore-dev
      - libexpat1-dev
      - libfaad-dev
      - libfftw3-dev
      - libflac-dev
      - libfluidsynth-dev
      - libgamin-dev
      - libglib2.0-dev
      - libgme-dev
      - libjack-dev
      - libmad0-dev
      - libmms-dev
      - libmodplug-dev
      - libmpcdec-dev
      #- libmpg123-dev
      - libofa0-dev
      #- libopusfile-dev
      - libperl-dev
      - libpulse-dev
      - libreadline-dev
      - libresid-builder-dev
      - libsamplerate0-dev
      - libsdl1.2-dev
      - libshout3-dev
      - libsidplay2-dev
      - libsmbclient-dev
      - libsndfile1-dev
      - libsqlite3-dev
      - libssl-dev
      - libvisual-0.4-dev
      - libvorbis-dev
      - libwavpack-dev
      - libxml2-dev
      - python-dev
      - python-all-dev
      - ruby-all-dev
      - valgrind
  coverity_scan:
    project:
      name: xmms2/xmms2-devel
    notification_email: coverity-notification@xmms2.org
    build_command_prepare: ./waf configure
    build_command: ./waf configure build
    branch_pattern: coverity_scan
