from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="wavpack", uselib_store="wavpack",
            args="--cflags --libs")

configure, build = plugin("wavpack", configure=plugin_configure,
        libs=["wavpack"])
