from waftools.plugin import plugin

def plugin_configure(conf):
    return conf.check_pkg('wavpack', destvar='wavpack')

configure, build = plugin('wavpack', needs_lib=True, configure=plugin_configure, source="wavpack.c")
