from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="wavpack", uselib_store="wavpack", args="--cflags --libs"):
        return False
    return True

configure, build = plugin("wavpack", configure=plugin_configure, source="wavpack.c", libs=["wavpack"])
