from waftools.plugin import plugin

def plugin_configure(conf):
    return True

def plugin_build(bld, obj):
    obj.find_sources_in_dirs('. libasf', excludes=['asf.c']) # TODO: fix waf to accept lists

configure, build = plugin('asf', configure=plugin_configure, source=[],
                          build=plugin_build, needs_lib=True)
