Import('base_env')

xmms2_sources = Split ("xmmsclient-qt.cpp")

env = base_env.Copy(CPPPATH = ['#src/clients/lib/xmmsclient', '#src', '/usr/include/qt3'],
	LIBPATH = ["../xmmsclient/"],
	LIBS = ["xmmsclient"],
	tools=['default', 'qt'])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("dbus")
env.AddFlagsFromGroup("qt")

env.XmmsLibrary("xmmsclient-qt", xmms2_sources)
