from waftools.plugin import plugin

def plugin_configure(conf):
    conf.env['CCDEFINES_mp4'] = ['USE_TAGGING']
    # to use iTunes DRM change this to true
    if False:
        conf.env['CCDEFINES_mp4'] += ['ITUNES_DRM', 'HAVE_SYS_STAT_H',
                                      'HAVE_ERRNO_H', 'HAVE_LIMITS_H',
                                      'HAVE_STRING_H']
    return conf.check_library2("m", uselib='math', mandatory=0)

def plugin_build(bld, obj):
    obj.find_sources_in_dirs('. mp4ff', excludes=['mp4.c']) # TODO: fix waf to accept lists

configure, build = plugin('mp4', configure=plugin_configure, build=plugin_build,
                          source=[], extra_libs=['math'], needs_lib=True)
