# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright XMMS2 Team
#

import os

def build(bld):
    platform_src = {'nt':'win32', 'posix':'unix'}

    obj = bld.create_obj('cc', 'staticlib')
    obj.source = "socket_common.c socket_%s.c" % platform_src[os.name]
    obj.includes='. ../../include'
    obj.target='xmmssocket'
    obj.install_in = 0

def configure(conf):
    pass

def set_options(opt):
    pass
