# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2007 XMMS2 Team
#

from Params import g_platform

def build(bld):
    obj = bld.create_obj('cc', 'staticlib')
    obj.source = ["socket_common.c"]
    if g_platform == 'win32':
        obj.source.append("socket_win32.c")
    else:
        obj.source.append("socket_unix.c")
    obj.includes='. ../../include'
    obj.target='xmmssocket'
    obj.install_var = 0

def configure(conf):
    pass

def set_options(opt):
    pass
