from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="libxml-2.0", uselib_store="xml2", args="--cflags --libs"):
        return False
    return True

configure, build = plugin('xspf', configure=plugin_configure, libs=["xml2"])
