
types_suite=["xmmsv/t_xmmsv.c", "xmmsv/t_coll.c"]

def configure(conf):
    if not conf.check_cc(header_name="CUnit/CUnit.h"):
        return False
    if not conf.check_cc(lib="cunit", uselib_store="cunit"):
        return False

    code = """
           static void T (void) __attribute__ ((constructor (220)));
           static void T (void) {};
    """
    if not conf.check_cc(fragment=code, type="objects", msg="Checking for constructor attribute"):
        return False

    conf.check_cfg(package='valgrind', uselib_store='valgrind', args='--cflags')

    return True

def build(bld):
    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_xmmstypes"
    obj.source = ['runner/main.c', 'runner/valgrind.c'] + types_suite
    obj.includes = '. runner/ ../src ../src/include'
    obj.uselib_local = 'xmmstypes'
    obj.uselib = 'cunit valgrind'
    obj.install_path = None

def set_options(o):
    pass
