from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_cfg(package="vorbisfile", uselib_store="vorbisfile",
                      args="--cflags --libs"):
        return True
    return False

configure, build = plugin('vorbis',
                          configure=plugin_configure,
                          source="vorbis.c",
                          libs=["vorbisfile"])
