from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="vorbisfile", uselib_store="vorbisfile", args="--cflags --libs"):
        return False
    return True

configure, build = plugin('vorbis', configure=plugin_configure, source="vorbis.c", libs=["vorbisfile"])
