from waftools.plugin import plugin

def plugin_configure(conf):
    for pkg in ("opus", "ogg", "opusfile"):
        if not conf.check_cfg(package=pkg, uselib_store=pkg, args="--cflags --libs"):
            return False
    return True

configure, build = plugin('opus', configure=plugin_configure, libs=["ogg", "opus", "opusfile"])
