import sys

def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_vocoder'
  obj.includes = '../../include'
  obj.source = ['vocoder.c', 'pvocoder.c']
  obj.uselib = 'fftw3f samplerate glib-2.0'

def configure(conf):
  if (conf.check_pkg('fftw3f', destvar='fftw3f') and
      conf.check_pkg('samplerate', destvar='samplerate')):
    conf.env['XMMS_PLUGINS_ENABLED'].append('vocoder')
