from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="fftw3f", uselib_store="fftw3f",
            args="--cflags --libs")
    conf.check_cfg(package="samplerate", uselib_store="samplerate",
            args="--cflags --libs")

configure, build = plugin('vocoder', configure=plugin_configure,
                          libs=["fftw3f", "samplerate"])
