MODULE += LIBXMMSCLIENT

LIBXMMSCLIENT_DIR = src/clients/lib/xmmsclient

LIBXMMSCLIENT_OBJS = 	medialib.o \
			other.o \
			playback.o \
			playlist.o \
			result.o \
			xhash.o \
			xlist.o \
			xmmsclient.o \
			xmmswatch.o 
LIBXMMSCLIENT_LIBRARIES = libxmmsclient.so
LIBXMMSCLIENT_DEPENDS = DBUS
