#clientlib

Import('base_env')

xmmsc_sources = Split ("xmmsclient.c")

env = base_env.Copy()

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("dbus")

env.SharedLibrary('xmmsclient', xmmsc_sources)
env.Install("/usr/local/lib/",env['LIBPREFIX']+"xmmsclient"+env['SHLIBSUFFIX'])
