#clientlib

Import('base_env')

xmmsc_sources = Split ("xmmsclient.c ipc.c ipc_glib.c playback.c playlist.c "
		       "xlist.c xhash.c result.c medialib.c other.c")

env = base_env.Copy(INCLUDES=["include"], LIBS=["xmmsipc", "xmmsutil"],
		    LIBPATH=["#builddir/lib/xmmsutil", "#builddir/lib/xmmsipc"])


#env.AddFlagsFromGroup("dbus")
env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("glib-thread")

if env.HasGroup ("ecore") :
	xmmsc_sources.append("ipc_ecore.c")
	env.AddFlagsFromGroup("ecore")

if base_env.sys == 'Darwin':
	env.AddFlagsFromGroup("Carbon")
	env.AddFlagsFromGroup("Cocoa")
	env.AddFlagsFromGroup("CoreFoundation")
	
	xmmsc_sources.append("ipc_carbon.c")
	xmmsc_sources.append("ipc_cocoa.c")
	

env.XmmsLibrary('xmmsclient', xmmsc_sources)

