def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmmsclient'
  obj.includes = '../../../include ../../../includepriv'
  obj.source = ['bindata.c', 'ipc.c', 'medialib.c', 'other.c', 'playback.c', 'playlist.c', 'result.c', 'xlist.c', 'xmmsclient.c', 'xqueue.c']
  obj.uselib_local = 'xmmsipc xmmssocket'

def configure(conf):
  pass

def set_options(opt):
  pass
