from waftools import tool

from Params import g_platform

def build(bld):
    obj = bld.create_obj('cc', 'shlib')
    obj.target = 'xmmsclient'
    obj.includes = '../../../include ../../../includepriv'
    obj.source = """
                 collection.c
                 collparser.c
                 bindata.c
                 config.c
                 ipc.c
                 medialib.c
                 playback.c
                 playlist.c
                 result.c
                 stats.c
                 xmmsclient.c
                 xform.c
                 xqueue.c
                 visualization/client.c
                 visualization/udp.c
                 """.split()
    if g_platform == 'win32':
        obj.source.append("visualization/dummy.c")
    else:
        obj.source.append("visualization/unixshm.c")
    obj.uselib_local = 'xmmsipc xmmssocket xmmsutils xmmstypes xmmsvisualization'
    obj.uselib = 'socket'
    obj.vnum = '4.0.0'
    tool.add_install_flag(bld, obj)

def configure(conf):
    conf.env.append_value('XMMS_PKGCONF_FILES', ('xmms2-client', '-lxmmsclient'))
    return True

def set_options(opt):
    pass
