#clientlib

Import('base_env')

xmmsc_sources = Split ("xmmsclient-glib.c")

env = base_env.Copy(CPPPATH = ['../xmmsclient', '#src/include'],
		    LIBPATH = ['../xmmsclient'],
		    LIBS = ['xmmsclient'])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("dbus")

env.XmmsLibrary('xmmsclient-glib', xmmsc_sources)

