from xmmsenv import tool

def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmmsclient-glib'
  obj.includes = '../../../include'
  obj.source = 'xmmsclient-glib.c'
  obj.uselib = 'glib2'
  obj.uselib_local = 'xmmsclient'
  tool.add_install_flag(obj)

def configure(conf):
  conf.env['XMMS_PKGCONF_FILES'].append(('xmms2-client-glib', '-lxmmsclient-glib'))
  return True

def set_options(opt):
  pass
