def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmmsclient-glib'
  obj.includes = '../../../include'
  obj.source = 'xmmsclient-glib.c'
  obj.uselib = 'glib-2.0'
  obj.uselib_local = 'xmmsclient'

def configure(conf):
  conf.check_pkg2('glib-2.0', version='2.6.0', uselib='glib-2.0')

def set_options(opt):
  pass
