import sys

def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'waveout'
  obj.sources = 'waveout.c'
  obj.uselib = 'waveout'

def configure(conf):
  conf.check_tool('checks')
  if conf.check_header2('windows.h', mandatory=0):
    conf.env['LIBS_waveout'] = 'winmm'
    conf.env['XMMS_PLUGINS_ENABLED'].append('waveout')
