def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_modplug'
  obj.includes = '../../include'
  obj.source = 'modplug.c'
  obj.uselib = 'modplug libmodplug glib-2.0'

def configure(conf):
  if (conf.check_pkg('modplug', destvar='modplug') or
      conf.check_pkg('libmodplug', destvar='libmodplug')):
    conf.env['XMMS_PLUGINS_ENABLED'].append('modplug')
