def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'modplug'
  obj.sources = 'modplug.c'
  obj.uselib = 'modplug libmodplug'

def configure(conf):
  modplug = conf.check_pkg('modplug', destvar='modplug')
  print modplug, type(modplug), bool(modplug)
  if (conf.check_pkg('modplug', destvar='modplug') or
      conf.check_pkg('libmodplug', destvar='libmodplug')):
    conf.env['XMMS_PLUGINS_ENABLED'].append('modplug')
