#cli client

Import('base_env')

xmms2_sources = Split ("xmms2_client.c")

env = base_env.Copy(CPPPATH = ['../lib/xmmsclient','../lib/xmmsclient-glib','#src'],
	LIBPATH = ["../lib/xmmsclient/", "../lib/xmmsclient-glib"],
	LIBS = ["xmmsclient", "xmmsclient-glib"])

env.AddFlagsFromGroup("glib")

env.XmmsProgram("xmms2", xmms2_sources)
