#cli client

Import('base_env')

xmms2_sources = Split ("xmms2_client.c")

env = base_env.Copy(CPPPATH = ['../lib/xmmsclient','../lib/xmmsclient-glib', '../lib/xmmsclient-sync', '#src'],
	LIBPATH = ["../lib/xmmsclient/", "../lib/xmmsclient-glib", "../lib/xmmsclient-sync"],
	LIBS = ["xmmsclient", "xmmsclient-glib", "xmmsclient-sync"])

env.AddFlagsFromGroup("glib")

env.XmmsProgram("xmms2", xmms2_sources)
