from Params import g_platform

def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.target = 'xmms2'
    obj.source = """cmd_config.c
                    cmd_mlib.c
                    cmd_other.c
                    cmd_playback.c
                    cmd_pls.c
                    cmd_status.c
                    cmd_coll.c
                    common.c
                    main.c""".split()
    if g_platform == 'win32':
        obj.source.append('common_win32.c')
    else:
        obj.source.append('common_unix.c')

    obj.includes = '. ../../include'
    obj.uselib_local = 'xmmsclient-glib xmmsclient'
    obj.uselib = 'glib2'

    obj = bld.create_obj('man')
    obj.files = ['xmms2.1']

def configure(conf):
    return True

def set_options(opt):
    pass
