def build(bld):
	obj = bld.create_obj('cc', 'program')
	obj.target = 'xmms2'
	obj.source = """cmd_config.c
					cmd_mlib.c
					cmd_other.c
					cmd_playback.c
					cmd_pls.c
					cmd_status.c
					cmd_coll.c
					common.c
					main.c""".split()
	obj.includes = '. ../../include'
	obj.uselib_local = 'xmmsclient-glib xmmsclient'
	obj.uselib = 'glib2'

def configure(conf):
	return True

def set_options(opt):
	pass
