.\" 
.\" xmms2 - A cli client for xmms2d
.\"
.\" xmms2.1 - xmms2 manpage 
.\"
.\" Copyright (C) 2005-2009 XMMS2 Team
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.\" $Id: xmms2.1,v 1.2 2005/07/29 07:24:59 alex Exp $
.\"
.TH XMMS2 1 
.SH NAME
xmms2 \- offers a simple command-line interface to the XMMS2 daemon
.SH SYNOPSIS
.I xmms2
.B command
.P
.I xmms2
.B mlib
.B command
.P
.I xmms2
.B playlist
.B command
.P
.I xmms2
.B coll
.B command 
.P
.SH DESCRIPTION
.B XMMS2 
is a redesign of the XMMS (http://www.xmms.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organize your music.
.PP
.I xmms2
is the official command-line interface client for
.B XMMS2
and acts as a reference implementation for the development of new clients. 
.I xmms2
is able to issue commands to control the active playlist and playback as well as commands to control the media library. 
.PP
The following commands effect the current
.B XMMS2
playlist.
.PP
.PP
.I xmms2
includes many commands that allow the user to execute actions on
.I xmms2d.
.TP
.BR
These commands are currently recognized: 
.TP
.I add [playlist] url...
Adds URL(s) to 
.I playlist
or the active playlist.
.TP
.I addarg [playlist] url arguments
Adds an URL to 
.I playlist
or the active playlist, with arguments.
.TP
.I addid [playlist] medialib_id...
Adds song(s) to 
.I playlist
or the active playlist using its Media Library ID.
.TP
.I addpls [playlist] url
Adds a playlist in a file to 
.I playlist
or the active playlist.
.TP
.I insert [playlist] pos url
Adds a URL to  
.I playlist
or the active playlist at a specific position.
.TP
.I insertid [playlist] pos medialib_id
Adds a song to 
.I playlist
or the active playlist at a specific position using its Media Library ID.
.TP
.I radd [playlist] directory
Adds a directory of songs recursively to 
.I playlist
or the active playlist.
.TP
.I clear [playlist]
Clears all entries from 
.I playlist
or the active playlist.
.TP
.I shuffle [playlist]
Places the songs in 
.I playlist
or the active playlist in a random order.
.TP
.I sort property
Sort the active playlist based on metadata from the Media Library. The metadata which is used for the sorting is based on what was given for 
.I property.
An overview of the media library, and the potential properties, can be found in the 
.B MEDIA LIBRARY
section of this manual page.
.TP
.I sort playlist properties
Sort
.I playlist
based on metadata from the Media Library. Separate the properties with a spaces.
.TP
.I remove [playlist] playlist_position
Removes a song from
.I playlist 
or the active playlist at the position given by 
.I playlist_position.
.TP
.I list [playlist]
Lists the contents of 
.I playlist
or the active playlist. An explanation of how to change the output format can be found in the
.B FILES
section of this manual page. 
.TP
.I play
Starts playback of the playlist.
.TP 
.I stop
Stops playback of the playlist.
.TP
.I toggleplay
Toggles playback status between play/pause
.TP
.I pause
Pauses playback of the playlist.
.TP
.I next
Skips to the next song in the playlist.
.TP
.I prev
Skips to the previous song in the playlist.
.TP
.I seek [+ / -]seconds
Seeks to a specific position in the currently playing song. The way in which 
.I seek
moves in the file is based on the arguments passed to it. If + is used 
.I xmms2
will seek 
.I seconds
forward in the song. If - is used
.I xmms2
will seek
.I seconds
backwards in the song. If merely a number of seconds is given 
.I xmms2
will seek to that absolute position in the song.
.TP
.I jump [+ / -]playlist_position
Jumps to 
.I playlist_position
in the playlist or
.I playlist_position
forward/backward if + or - is specified.
.TP
.I move [playlist] playlist_position new_position
Moves the song at
.I playlist position
to the position denoted by
.I new_position in
.I playlist
or the active playlist.
.TP
.I volume channel volume
Sets the volume of 
.I channel
to 
.I volume.
.TP
.I volume_list
Lists the volume for each channel.
.TP 
.I mlib
Allows for the manipulation of the Media Library. The significance of the sub-commands of 
.I mlib
can be found in the 
.B MEDIA LIBRARY
section of this manual page.
.TP
.I playlist
Allows for the manipulation of playlists. The significance of the sub-commands of
.I playlist
can be found in the
.B PLAYLIST
section of this manual page.
.TP
.I coll
Allows for the manipulation of collections. The significance of this sub-commands of
.I coll
can be found in the
.B COLLECTIONS
section of this manual page.
.TP
.I browse url
Lists the contents of
.I url
in a list of encoded urls.
.TP
.I status
Gives a live status of the currently playing song.
.TP
.I info [id]
Gives the metadata archived by the Media Library for Media Library id
.I id
or the currently playing song.
.TP
.I current [pattern]
Gives some summary of the currently playing song's meta data. A pattern can be specified in the form "${album} \- ${tracknr}". Please be aware of your shells substitution features.
.TP
.I config config_key [=] value
Sets
.I config_key
to
.I value
on 
.I xmms2d(8).
.TP
.I config_list
Lists all the configuration values of 
.B XMMS2.
.TP
.I plugin_list
Prints a list of the plugins being used by
.B XMMS2.
.TP 
.I stats
Retrieves the uptime and version from 
.B XMMS2.
.TP
.I quit
Makes 
.I xmms2d(8)
quit.
.TP
.I help
Prints a concise overview of all commands offered by
.I xmms2.
.SH "MEDIA LIBRARY"
.B XMMS2
stores metadata about every song in the Media Library.
One can retrieve data from the Media Library using the 
.I mlib 
command of 
.I xmms2.
The Media Library is an SQL database which is created and accessed by use of the sqlite library.
.I xmms2 mlib
includes many commands for manipulating and retrieving data from the Media Library.
.TP
.BR
The following 
.I mlib 
commands are currently recognized:
.TP 
.I add url
Adds a URL to the Media Library but not to the current playlist. The Media Library also fetches associated metadata for the added song.
.TP 
.I loadall
Load all songs in the Media Library into the current playlist.
.TP
.I searchadd pattern
Searches the Media Library for songs that match 
.I pattern
criteria and adds them to the current playlist.
.TP
.I search pattern
Searches and returns a list of songs in the Media Library that match 
.I pattern.
.IP 
For example one could execute:
.IP
.I xmms2 mlib search artist:Dismantled
.IP
The result of which would be that all songs by Dismantled in the Media Library would be listed.
.TP
.I addpath path
Adds all songs in directory
.I path
into the Media Library.
.TP
.I rehash
Force the Media Library to check whether its data is up to date.  
.TP
.I remove id
Removes a song from the Media Library with the id
.I id.
.TP
.I setstr id key value [source]
sets a string Media Library property with key
.I key
and value
.I value
for song with ID
.I id.
Optionally a source can be supplied with the 
.I source
argument. If no source is defined client/xmms2-cli will be used.
.TP
.I setint id key value [source]
Sets a string Media Library property with key
.I key
and value
.I value
for song with ID
.I id.
Optionally a source can be supplied with the 
.I source
argument. If no source is defined client/xmms2-cli will be used.
.TP
.I rmprop id key [source]
Removes properties from the Media Library entry with
.I id
and with key
.I key
and optionally source
.I source.
.TP
.I addcover file id
Add a cover image for id(s)
.I id.
.PP
The Media Library allows for any variety of keys (sometimes called properties) to be stored within. There is no set list of available keys but rather the Media Library can store any variety of different values. For this reason it is difficult to give a complete list of available keys but some examples are:
.TP
.I url
The path to the song in url
.TP
.I added
The time in seconds since UTC 00:00:00, 1 Jan 1970 that the song was added to the Media Library
.TP
.I mime
The MIME type of the song in the Media Library
.TP
.I lmod
The last time in seconds since UTC 00:00:00, 1 Jan 1970 that the song was modified
.TP 
.I laststarted
The last time the song was played
.TP
.I timesplayed
The number of times the song was played
.TP
.I duration
The length of the song in milliseconds
.TP
.I bitrate
The bitrate of the song in bps
.TP
.I album
The name of the album the song is on
.TP
.I artist
The name of the artist that produced the song
.TP
.I title
The title of the song
.TP
.I tracknr
The track number of the song
.TP
.I {album, artist, track}_id
MusicBrainz ID numbers for the song
.SH "PLAYLIST"
.B XMMS2
has support for playlists which is tightly coupled with
.B XMMS2's
Collections system. Playlist manipulation is accessible with the
.I playlist
command of
.I xmms2.
.I xmms2 playlist
includes many commands for manipulating and retrieving data about playlists.
.TP
.BR
The following
.I playlist
commands are currently recognized:
.TP
.I list
Lists all currently available playlists.
.TP
.I create [playlistname]
Create a new playlist named
.I playlistname.
.TP
.I type [playlistname] [type]
Sets type of the playlist named
.I playlistname
to type
.I type.
Descriptions of the available types can be found
later in the
.B PLAYLIST
section of this manual page.
.TP
.I load [playlistname]
Load a playlist specified by
.I playlistname
from the Media Library
.TP
.I remove [playlistname]
Remove a playlist specified by
.I playlistname
from the Media Library
.PP
.B XMMS2
currently supports three types of playlists, each of these playlists has a number of attributes which can
be set using the
.I coll attr
command described in the
.B COLLECTIONS
section of this manual page.
The available playlist types are:
.TP
.I list
A simple list of medialib ids.
The
.I list
has one attribute:
.P
.I jumplist
which is the name of a playlist to jump to when the list is finished.
.TP
.I queue
A static playlist which supports a fixed length playlist where songs are removed as they are played.
The
.I queue
has two attributes:
.P
.I jumplist
which is the name of a playlist to jump to when the queue is finished
.P
.I history
which is the number of played entries to keep before beginning to remove them
.TP
.I pshuffle
A playlist which picks a configurable number of songs from a collection at random.
The
.I pshuffle
has three attributes:
.P
.I jumplist
which is the name of a playlist to jump to when the pshuffle is finished. A pshuffle playlist only finishes when the collection from which new songs are pulled dries up, for instance when filtering on timesplayed < 1
.P
.I history
which is the number of played entries to keep before beginning to remove them
.P
.I upcoming
which is the number of unplayed entries to show in the playlist
.SH COLLECTIONS
.B XMMS2
includes an extremely powerful method for querying and selecting music from the Media Library
called Collections. Some of the features of collections are made accessible via the
.I xmms2
client.
.I xmms2 coll
includes many commands for manipulating and retrieving data about Collections.
.TP
.BR
The following
.I coll 
commands are currently recognized:
.TP
.I save [collname] [pattern]
Save the pattern
.I pattern
as a Collection named
.I collname
.TP
.I rename [oldname] [newname]
Rename a Collection from
.I oldname
to
.I newname.
.TP
.I list [namespace]
List all Collections, or if
.I namespace
is specified list only collections in the
Collections or Playlists namespace.
.TP
.I query [collname] [order]
Retrieve information about all media in the Collection
named
.I collname
ordered by
.I order
.TP
.I queryadd [collname] [order]
Add all media from the Collection
.I collname
ordered by
.I order
to the active playlist
.TP
.I find [mid] [namespace]
Find all collections in
.I namespace
that include the media referenced by
.I mid
.TP
.I get [collname]
Display information about the Collection
.I collname
.TP
.I remove [collname]
Remove the collection referenced by
.I collname
.TP
.I attr [collname] [attr] [val]
Set or get an attribute of name
.I attr
to value
.I val
on Collection
.I collname
.PP
.I xmms2
sometimes requires that the namespace of a Collection be specified in
.I collname.
This is done by prepending either
.I Playlists/
or
.I Collections/
to the beginning of the Collection name. If not specified the namespace defaults to 
.I Collections.
.SH FILES
.TP
.I $XDG_CONFIG_HOME/xmms2/clients/cli.conf or $HOME/Library/xmms2/clients/cli.conf or $HOME/.config/xmms2/clients/cli.conf
A configuration file containing basic configuration values for 
.I xmms2,
including the output format used by the
.I list
and
.I status
commands.
.SH ENVIRONMENTAL VARIABLES
.TP
.I XMMS_PATH
The URL path to 
.I xmms2d.
.TP
.I XDG_CONFIG_HOME
The path where the xmms2 configuration files are located
See
.B IPC SOCKET
in  
.I xmms2d(8)
for details of possible values for this variable

.SH SEE ALSO
xmms2d(8), http://xmms2.xmms.org
.SH HISTORY
The
.B XMMS2
Project was started by Tobias Rundström and Anders Gustafsson. It is developed with their lead by a small group of contributors from all over the world.
.SH AUTHOR
This manual page was written by Alexander Botero-Lowry <alex@foxybanana.com>
