from waftools.plugin import plugin

def plugin_configure(conf):
    return conf.check_pkg2('libmpg123', '1.5.1', mandatory=False, uselib='mpg123')

configure, build = plugin('mpg123', configure=plugin_configure,
                          source=['mpg123.c', 'id3v1.c'], needs_lib=True)
