from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_header('mpg123.h'):
        return False

    return conf.check_library2('mpg123', uselib='mpg123', mandatory=0)

configure, build = plugin('mpg123', configure=plugin_configure,
                          source=['mpg123.c', 'id3v1.c'], needs_lib=True)
