Import('base_env')

if base_env.HasGroup ("python"):
	pyx = Builder(action = "(" + base_env["PYREX"] + ' $SOURCE' + " || true)")
	env = base_env.Copy (CPPPATH = ['#src', '#src/include'],
			     LIBPATH = ["#builddir/clients/lib/xmmsclient/"],
			     LIBS = ["xmmsclient"])

	env.Append(BUILDERS = {'Pyx' : pyx})
	env['CCFLAGS'] += ' -Wno-unused-function -Wno-unused-label'

	env.AddFlagsFromGroup ("glib")
	env.AddFlagsFromGroup ("python")
	if base_env.HasGroup ("pyrex") :
		env.Pyx ("xmmsclient.c", ["xmmsclient.pyx"])
		env.XmmsPython ("xmmsclient", ["xmmsclient.c"])
