import os
import Params
import Common

def build(bld):
    obj = bld.create_obj('cc', 'plugin', 'pyext')
    obj.target = 'xmmsapi'
    obj.includes = '../../../include ../../../includepriv .'
    obj.source = ['xmmsapi.pyx']
    obj.uselib_local = 'xmmsclient'
    obj.install_var = "xmmsclient_PYTHONDIR"

    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/__init__.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/sync.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/propdict.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/consts.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/collections.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/glib.py')
    Common.install_files('xmmsclient_PYTHONDIR', '', 'xmmsclient/qt3.py')

def configure(conf):
    if not (conf.check_tool('python') and
            conf.check_python_version() and
            conf.check_python_headers()):
        return False

    conf.env['xmmsclient_PYTHONDIR'] = os.path.join(conf.env['PYTHONDIR'], 'xmmsclient')

    return conf.check_tool('pyrexc', tooldir=os.path.abspath('waftools'))

def set_options(opt):
    pass

