def build(bld):
    tskgen = bld(features = 'c',
        target = 'valgrind_object',
        source = ['valgrind.c'],
        includes = '. ..',
        uselib = 'valgrind DISABLE_UNUSEDBUTSETVARIABLE',
        install_path = None,
        )

    if bld.env.HAVE_VALGRIND:
        tskgen.defines = ["HAVE_VALGRIND=1"]

def configure(conf):
    return True

def options(opt):
    pass
