def build(bld):
    obj = bld.new_task_gen('cc', 'program')
    obj.target = 'nyxmms2'
    obj.source = """main.c
                    cli_infos.c
                    cli_cache.c
                    command_trie.c
                    commands.c
                    command_utils.c
		    cmdnames.c
		    configuration.c
		    status.c		    
		    utils.c
		    alias.c
                    column_display.c
                    readline.c
                    playlist_positions.c""".split()
    obj.includes = '. ../../include'
    obj.uselib_local = 'xmmsclient'
    obj.uselib = 'glib2 readline readline-ncurses'

    obj = bld.new_task_gen(features='man', files='nyxmms2.1', section='1')

def configure(conf):
    rl_headers=["stdio.h", "readline/readline.h"]

    conf.check_cc(header_name=rl_headers, mandatory=True)

    # first try just linking against libreadline
    if conf.check_cc(lib="readline", header_name=rl_headers, uselib_store="readline"):
        return

    # then try ncurses
    conf.check_cc(lib="ncurses", uselib_store="readline-ncurses", mandatory=True)

    if conf.check_cc(lib="readline", header_name=rl_headers, uselib_store="readline", uselib="readline-ncurses"):
        return

    # Ok, we give up..
    conf.fatal("Cannot build nycli")

def set_options(opt):
    pass
