def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.target = 'nyxmms2'
    obj.source = """main.c""".split()
    obj.includes = '. ../../include'
    obj.uselib_local = 'xmmsclient-glib xmmsclient'
    obj.uselib = 'glib2'

#    obj = bld.create_obj('man')
#    obj.files = ['xmms2.1']

def configure(conf):
    return True

def set_options(opt):
    pass
