def build(bld):
    obj = bld.new_task_gen('cc', 'program')
    obj.target = 'nyxmms2'
    obj.source = """main.c
                    cli_infos.c
                    cli_cache.c
                    command_trie.c
                    commands.c
                    command_utils.c
		    cmdnames.c
		    configuration.c
		    status.c		    
		    utils.c
		    alias.c
                    column_display.c
                    readline.c
                    playlist_positions.c""".split()
    obj.includes = '. ../../include'
    obj.uselib_local = 'xmmsclient'
    obj.uselib = 'glib2 readline readline-ncurses'

#    obj = bld.create_obj('man')
#    obj.files = ['xmms2.1']

def configure(conf):
    if not conf.check_cc(header_name="readline/readline.h"):
        return False

    # first try just linking against libreadline
    if conf.check_cc(lib="readline", header_name="readline/readline.h", function_name='rl_filename_dequoting_function', uselib_store="readline"):
        return True

    # then try ncurses
    if not conf.check_cc(lib="ncurses", header_name="readline/readline.h", function_name='rl_filename_dequoting_function', uselib_store="readline-ncurses"):
        return False
    if conf.check_cc(lib="readline", uselib_store="readline", uselib="readline-ncurses"):
        return True

    # Ok, we give up..
    return False

def set_options(opt):
    pass
