.\" xmms2 - The official XMMS2 command line interface
.\"
.\" xmms2.1 - The xmms2 man page
.\"
.\" Copyright (C) 2009 Anthony Garcia
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH XMMS2 1
.SH NAME
xmms2 \- The official XMMS2 command line interface
.SH SYNOPSIS
.B xmms2
[command]
[arguments]
.br
.B xmms2 help
[command]
.SH DESCRIPTION
XMMS2 is a redesign of the XMMS (http://legacy.xmms2.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organise your music.
.PP
.B xmms2
is the official CLI XMMS2 client.
.SH INVOCATION
.SS Inline mode
If
.B xmms2
is passed a command as an argument, that command will be interpreted and
.B xmms2
will exit after it is finished.
.SS Interactive mode
.B xmms2
features a powerful shell-like environment via readline that allows the user to
enter commands at a prompt and have the usual cool features such as pathname
expansion and line editing.
.SH COMMANDS
.PP
All commands accept the option \fB-h\fR/\fB--help\fR which displays the command's help.
.PP
\fIpattern\fR refers to a collection definition. (See \fBPATTERN\fR below.)
.PP
\fIposition\fR is a pattern to match playlist positions. (See \fBPOSITION PATTERN\fR below.)
.SS General Commands
.T
\fBadd\fR [ \fB\-f\fR [\fB\-N\fR] [\fB\-P\fR] [\fB\-A\fR \fIkey=value\fR]... ] [\fB\-p\fR \fIplaylist\fR] [\fB\-n\fR | \fB\-a\fR \fIposition\fR] [\fB-o\fR \fIprop\fR[,...]] \fIarguments\fR...
.br
\fBadd\fR [\fB\-p\fR \fIplaylist\fR] [\fB\-n\fR | \fB\-a\fR \fIposition\fR] [\fB-o\fR \fIprop\fR[,...]] \fIpattern\fR...
.PP
.RS 4
Add media to a playlist. It will attempt to guess whether \fIarguments\fR
constitute a \fIpattern\fR or represent file paths. This behaviour can be overridden by
forcing the type with \fB-f\fR and \fB-t\fR. If file paths contain * or ?
characters, it will attempt to expand them. Failing to find a match the * and ? characters
will be attempted to be added as a part of the URL.
.RE
.PP
.RS 4
\fB\-f\fR, \fB\-\-file\fR
.RE
.RS 8
Force treating \fIarguments\fR as file paths.
.RE
.PP
.RS 4
\fB\-P\fR, \fB\-\-pls\fR
.RE
.RS 8
Force treating \fIarguments\fR as playlist files. This option implies \fB-f\fR.
.RE
.PP
.RS 4
\fB\-t\fR, \fB\-\-pattern\fR
.RE
.RS 8
Force treating \fIarguments\fR as a pattern.
.RE
.PP
.RS 4
\fB\-N\fR, \fB\-\-non-recursive\fR
.RE
.RS 8
Do not add directories recursively.
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR \fIplaylist\fR
.RE
.RS 8
Add media to \fIplaylist\fR instead of the active playlist.
.RE
.PP
.RS 4
\fB\-n\fR, \fB\-\-next\fR
.RE
.RS 8
Add media after the current track.
.RE
.PP
.RS 4
\fB\-a\fR, \fB\-\-at\fR \fIposition\fR
.RE
.RS 8
Add media at the given position.
.RE
.PP
.RS 4
\fB\-A\fR, \fB\-\-attribute\fR \fIkey=value\fR
.RE
.RS 8
Add media with given key=value attribute. May occur multiple times. Only
valid when adding new files to the media library.
.RE
.PP
.RS 4
\fB\-o\fR, \fB\-\-order\fR \fIprop\fR[,...]
.RE
.RS 8
Add media sorted by the given comma-separated list of properties. If a property
is prefixed by \-, media are sorted in reverse order on that property.
.RE
.PP

.TP
\fBexit\fR
.PP
.RS 4
Exit the shell-like interface.
.RE
.PP

.TP
\fBhelp\fR [\fB\-a\fR] \fIcommand\fR
.PP
.RS 4
Show the help on \fIcommand\fR. This is equivalent to \fBcommand -h\fR.
If \fIcommand\fR is an alias, show the alias definition.
If no command is provided, list all available commands.
.RE
.PP
.RS 4
\fB\-a\fR, \fB\-\-alias\fR
.RE
.RS 8
List available aliases if \fIcommand\fR is not provided. Otherwise, have no
effect.
.RE
.PP

.TP
\fBinfo\fR [\fIpattern\fR | \fIpositions\fR...]
.PP
.RS 4
Display the properties of all media matching \fIpattern\fR or at the given
positions. Without argument, display the properties of the current
track.
.RE
.PP

.TP
\fBjump\fR [\fB\-b\fR] \fIpattern\fR|\fIposition\fR
.PP
.RS 4
Jump to the first media matching \fIpattern\fR or to the given position.
.RE
.PP
.RS 4
\fB\-b\fR, \fB\-\-backward\fR
.RE
.RS 8
Jump backward to the first media matching the pattern
.RE
.PP

.TP
\fBlist\fR [\fB\-p\fR \fIname\fR] [\fIpattern\fR | \fIpositions\fR...]
.PP
.RS 4
List the contents of a playlist (the active one by default).
If \fIpattern\fR is provided, contents are further filtered and only the
matching media are displayed.
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR
.RE
.RS 8
List \fIplaylist\fR, instead of the active playlist.
.RE
.PP

.TP
\fBmove\fR [\fB\-p\fR \fIplaylist\fR] [\fB\-n\fR | \fB\-a\fR \fIposition\fR] \fIpattern\fR | \fIpositions\fR...
.PP
.RS 4
Move entries inside a playlist (the active one by default).
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR \fIplaylist\fR
.RE
.RS 8
The \fIplaylist\fR to act on.
.RE
.PP
.RS 4
\fB\-n\fR, \fB\-\-next\fR
.RE
.RS 8
Move the matching tracks after the current track.
.RE
.PP
.RS 4
\fB\-a\fR, \fB\-\-at\fR \fIposition\fR
.RE
.RS 8
Move the matching tracks by an offset or to a \fIposition\fR.
.RE
.PP

.TP
\fBnext\fR [\fIoffset\fR]
.PP
.RS 4
Jump to the next song. If \fIoffset\fR is provided, act like \fBjump +\fIoffset\fR.
.RE
.PP

.TP
\fBpause\fR
.PP
.RS 4
Pause playback.
.RE
.PP

.TP
\fBplay\fR
.PP
.RS 4
Start playback.
.RE
.PP

.TP
\fBprev\fR [\fIoffset\fR]
.PP
.RS 4
Jump to the previous song. If \fIoffset\fR is provided, act like \fBjump -\fIoffset\fR.
.RE
.PP

.TP
\fBremove\fR [\fB\-p\fR \fIplaylist\fR] \fIpattern\fR | \fIpositions...\fR
.PP
.RS 4
Remove the matching media from a playlist (the active one by default).
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR \fIplaylist\fR
.RE
.RS 8
Remove from \fIplaylist\fR, instead of the active playlist.
.RE
.PP

.TP
\fBcurrent\fR [\fB\-r\fR \fIseconds\fR] [\fB\-f\fR \fIformat\fR]
.PP
.RS 4
Display playback status, either continuously or once.
.RE
.PP
.RS 4
\fB\-r\fR, \fB\-\-refresh\fR \fIseconds\fR
.RE
.RS 8
Set the delay, in seconds, between each refresh of the current playback metadata.
If 0, the metadata is only printed once (default) and the command exit immediately.
When in refresh mode, basic control is provided on the active playlist.
.RE
.PP
.RS 4
\fB\-f\fR, \fB\-\-format\fR \fIformat\fR
.RE
.RS 8
Set the format string used to display status informations, instead of the one
from the configuration file (see \fBFORMAT STRING\fR below).
.RE
.PP

.TP
\fBsearch\fR [\fB\-o\fR \fIprop1\fR[,\fIprop2\fR...]] [\fB\-l\fR \fIprop1\fR[,\fIprop2\fR...] ] \fIpattern\fR
.PP
.RS 4
Search and print all media matching \fIpattern\fR.
.RE
.PP
.RS 4
\fB\-o\fR, \fB\-\-order\fR \fIprop1\fR[,\fIprop2\fR...]
.RE
.RS 8
Display search results sorted by the given list of properties. If a property is
prefixed by '-', results are sorted in reverse order on that property.
.RE
.PP
.RS 4
\fB\-l\fR, \fB\-\-columns\fR \fIprop1\fR[,\fIprop2\fR...]
.RE
.RS 8
List of \fIproperties\fR to use as columns.
.RE
.PP

.TP
\fBseek\fR \fItime\fR | \fIoffset\fR
.PP
.RS 4
Seek to a relative or an absolute time in the current track.
.RE
.PP

.TP
\fBstop\fR
.PP
.RS 4
Stop playback.
.RE
.PP

.TP
\fBtoggle\fR
.PP
.RS 4
Toggle playback.
.RE
.PP

.SS Playlist Commands
.BR

.TP
\fBplaylist clear\fR [\fIplaylist\fR]
.PP
.RS 4
Clear a playlist. By default, clear the active playlist.
.RE
.PP

.TP
\fBplaylist config\fR [\fB\-t\fR \fItype\fR] [\fB\-s\fR \fIhistory\fR] [\fB\-u\fR \fIupcoming\fR] [\fB\-i\fR \fIcoll\fR] [\fB-j\fR \fIplaylist\fR] [\fIplaylist\fR]
.PP
.RS 4
Configure a playlist by changing its type, attributes, etc.
By default, configure the active playlist.
.RE
.PP
.RS 4
\fB\-t\fR, \fB\-\-type\fR \fItype\fR
.RE
.RS 8
Change the \fItype\fR of the playlist: list, queue, pshuffle.
.RE
.PP
.RS 4
\fB\-s\fR, \fB\-\-history\fR \fIsize\fR
.RE
.RS 8
The \fIsize\fR of the history of played tracks (for queue, pshuffle).
.RE
.PP
.RS 4
\fB\-u\fR, \fB\-\-upcoming\fR \fIupcoming\fR
.RE
.RS 8
Number of \fIupcoming\fR tracks to maintain (for pshuffle).
.RE
.PP
.RS 4
\fB\-i\fR, \fB\-\-input\fR \fIcollection\fR
.RE
.RS 8
Input \fIcollection\fR for the playlist (for pshuffle). Default to 'All Media'.
.RE
.PP
.RS 4
\fB\-j\fR, \fB\-\-jumplist\fR \fIplaylist\fR
.RE
.RS 8
Jump to another \fIplaylist\fR when the end of the playlist is reached.
.RE
.PP

.TP
\fBplaylist create\fR [\fB\-p\fR \fIplaylist\fR] \fIname\fR
.PP
.RS 4
Create a new playlist.
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR \fIplaylist\fR
.RE
.RS 8
Copy the content of the playlist into the new playlist.
.RE
.PP

.TP
\fBplaylist list\fR [\fB\-a\fR]
.PP
.RS 4
List all playlists.
.RE
.PP
.RS 4
\fB\-a\fR, \fB\-\-all\fR
.RE
.RS 8
Include hidden playlists.
.RE
.PP

.TP
\fBplaylist remove\fR \fIplaylist\fR
.PP
.RS 4
Remove the given playlist.
.RE
.PP

.TP
\fBplaylist rename\fR [\fB\-f\fR] [\fB\-p\fR \fIplaylist\fR] \fInewname\fR
.PP
.RS 4
Rename a playlist.  By default, rename the active playlist.
.RE
.PP
.RS 4
\fB\-f\fR, \fB\-\-force\fR
.RE
.RS 8
Force the rename of the playlist, overwrite an existing playlist if needed.
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR
.RE
.RS 8
Rename the given playlist.
.RE
.PP

.TP
\fBplaylist shuffle\fR [\fIplaylist\fR]
.PP
.RS 4
Shuffle a playlist.  By default, shuffle the active playlist.
.RE
.PP

.TP
\fBplaylist sort\fR [\fB\-p\fR \fIplaylist\fR] [\fIprop\fR] ...
.PP
.RS 4
Sort a playlist. By default, sort the active playlist. Prefix properties by '-'
for reverse sorting.
.RE
.PP
.RS 4
\fB\-p\fR, \fB\-\-playlist\fR
.RE
.RS 8
Rename the given playlist.
.RE
.PP

.TP
\fBplaylist switch\fR \fIplaylist\fR
.PP
.RS 4
Change the active playlist.
.RE
.PP

.SS Collection Commands
.BR

.TP
\fBcollection config\fR \fIcollection\fR [\fIattrname\fR [\fIattrvalue\fR]]
.PP
.RS 4
Get or set attributes for the given collection.
If no attribute name is provided, list all attributes.
If only an attribute name is provided, display the value of the attribute.
If both attribute name and value are provided, set the new value of the attribute.
.RE
.PP

.TP
\fBcollection create\fR [\fB\-f\fR] [\fB\-e\fR] [\fB\-c\fR \fIcollection\fR] \fIname\fR [\fIpattern\fR]
.PP
.RS 4
Create a new collection.
If pattern is provided, it is used to define the collection.
Otherwise, the new collection contains the whole media library.
.RE
.PP
.RS 4
\fB\-f\fR, \fB\-\-force\fR
.RE
.RS 8
Force creating of the collection, overwrite an existing collection if needed.
.RE
.PP
.RS 4
\fB\-c\fR, \fB\-\-collection\fR \fIcollection\fR
.RE
.RS 8
Copy an existing collection to the new one.
.RE
.PP
.RS 4
\fB\-e\fR, \fB\-\-empty\fR
.RE
.RS 8
Initialize an empty collection.
.RE
.PP

.TP
\fBcollection list\fR
.PP
.RS 4
List all collections.
.RE
.PP

.TP
\fBcollection show\fR \fIcollection\fR
.PP
.RS 4
Display a human-readable description of a collection.
.RE
.PP

.TP
\fBcollection remove\fR \fIcollection\fR
.PP
.RS 4
Remove a collection.
.RE
.PP

.TP
\fBcollection rename\fR [\fB\-f\fR] \fIoldname\fR \fInewname\fR
.PP
.RS 4
Rename a collection.
.RE
.PP
.RS 4
\fB\-f\fR, \fB\-\-force\fR
.RE
.RS 8
Force renaming of the collection, overwrite an existing collection if needed.
.RE
.PP

.SS Server Commands
.BR

.TP
\fBserver browse\fR \fIURL\fR
.PP
.RS 4
Browse a URL via the xform plugins available in the daemon.
.RE
.PP

.TP
\fBserver config\fR [\fIname\fR [\fIvalue\fR]]
.PP
.RS 4
Get or set configuration values.
If no name or value is provided, list all configuration values.
If only a name is provided, display the content of the corresponding configuration value.
If both name and a value are provided, set the new content of the configuration value.
.RE
.PP

.TP
\fBserver import\fR [\fB\-N\fR] \fIpath\fR
.PP
.RS 4
Import new files into the media library.
By default, directories are imported recursively.
.RE
.PP
.RS 4
\fB\-N\fR, \fB\-\-non-recursive\fR
.RE
.RS 8
Do not import directories recursively.
.RE
.PP

.TP
\fBserver plugins\fR
.PP
.RS 4
List the plugins loaded in the server.
.RE
.PP

.TP
\fBserver property\fR [\fB\-i\fR | \fB\-s\fR | \fB\-D\fR] [\fB\-S\fR] \fImid\fR [\fIname\fR [\fIvalue\fR]]
.PP
.RS 4
Get or set properties for a given media.
If no name or value is provided, list all properties.
If only a name is provided, display the value of the property.
If both a name and a value are provided, set the new value of the property.

By default, set operations use source "client/xmms2-cli", while list and display operations use source-preference.
Use the \fB\-\-source\fR option to override this behaviour.

By default, the value will be used to determine whether it should be saved as a string or an integer.
Use the \fB\-\-int\fR or \fB\-\-string\fR flag to override this behaviour.
.RE
.PP
.RS 4
\fB\-i\fR, \fB\-\-int\fR
.RE
.RS 8
Force the value to be treated as integer.
.RE
.PP
.RS 4
\fB\-s\fR, \fB\-\-string\fR
.RE
.RS 8
Force the value to be treated as a string.
.RE
.PP
.RS 4
\fB\-D\fR, \fB\-\-delete\fR
.RE
.RS 8
Delete the selected property.
.RE
.PP
.RS 4
\fB\-S\fR, \fB\-\-source\fR
.RE
.RS 8
Property source.
.RE
.PP

.TP
\fBserver rehash\fR [\fIpattern\fR]
.PP
.RS 4
Rehash the media matched by the pattern,
or the whole media library if no pattern is provided
.RE
.PP

.TP
\fBserver remove\fR [\fIpattern\fR]
.PP
.RS 4
Remove the matching media from the media library.
.RE
.PP

.TP
\fBserver shutdown\fR
.PP
.RS 4
Shutdown the server.
.RE
.PP

.TP
\fBserver stats\fR
.PP
.RS 4
Display statistics about the server: uptime, version, size of the medialib, etc.
.RE
.PP

.TP
\fBserver sync\fR
.PP
.RS 4
Immediately save collections to disk. (Otherwise only performed on shutdown or 10 seconds after last change to collections.)
.RE
.PP

.TP
\fBserver volume\fR [\fB\-c\fR \fIname\fR] [\fIvalue\fR]
.PP
.RS 4
Get or set the audio volume (in a range of 0-100).
If a value is provided, set the volume to \fIvalue\fR. Otherwise, display the current volume.
By default, the command applies to all audio channels. Use the \fB\-\-channel\fR flag to override this behaviour.
Relative changes to the volume are possible by prefixing \fIvalue\fR by \fB+\fR or \fB-\fR.
.RE
.PP
.RS 4
\fB\-c\fR, \fB\-\-channel\fR
.RE
.RS 8
Get or set the volume only for the named channel.
.RE
.PP

.SH PATTERN
Patterns are used to search for songs in the media library, some of these patterns may require escaping (with '\\') depending on what shell is used. The properties can be found in the output of \fBxmms2 info\fR.
.PP

.TP
<property>\fB:\fR<string>
.PP
.RS 4
Match songs whose property matches the string. A \fI?\fR in the string indicates a single wildcard character, and a \fI*\fR indicates multiple wildcard characters.
.RE

.TP
<property>\fB~\fR<string>
.PP
.RS 4
Match songs whose property fuzzily matches the string. Equal to matching by <property>\fB:\fR*<string>*.
.RE

.TP
<property><operation><number>
.PP
.RS 4
The operation can be \fB<\fR, \fB<=\fR, \fB>\fR or \fB>=\fR, the pattern will
match songs whose property is a numerical value smaller, smaller or equal, bigger, bigger or equal in comparison to the number.
.RE

.TP
\fB+\fR<property>
.PP
.RS 4
Match songs which has the property.
.RE

.TP
\fBNOT\fR <pattern>
.PP
.RS 4
Match the complement of the pattern.
.RE

.T
<pattern> <pattern>
.br
<pattern> \fBAND\fR <pattern>
.PP
.RS 4
Match songs that are matched by both patterns.
.RE

.TP
<pattern> \fBOR\fR <pattern>
.PP
.RS 4
Match songs that are matched by at least one of the two pattern.
.RE

.TP
\fB(\fR <pattern> \fB)\fR
.PP
.RS 4
Match songs matched by the pattern, used for grouping AND and OR matches.
.RE

.TP
<string>
.PP
.RS 4
Match songs whose artist, title or album match the string.
.RE

.TP
\fB#\fR<number>
.PP
.RS 4
Match a specific media library id.
.RE

.SH POSITION PATTERN
Position patterns are used together with commands that operate on playlist content.
.TP
\fBM\fR_\fBN\fR
.PP
.RS 4
Select playlist entries ranging from \fBM\fR positions before the current song, to \fBN\fR positions after. Both \fBM\fR and \fBN\fR may be omitted and will then default to 0.
.RE

.TP
-\fBN\fR
.PP
.RS 4
Select the song \fBN\fR positions before the current song.
.RE

.TP
+\fBN\fR
.PP
.RS 4
Select the song \fBN\fR positions after the current song.
.RE

.TP
\fBpos0\fR,\fBpos1\fR,...,\fBposN\fR
.PP
.RS 4
Select one to many playlist positions.
.RE

.SH FORMAT STRING
.PP
Commands that output formatted metadata can be customized with the help
of user-defined format strings like the following:

.PP
\'${artist} - ${title}\'
.RE

When passed metadata the name of the artist and the title will be inserted into the resulting string. In addition to the metadata supplied from the media library the following list of properties are also available:

.TP
\fBposition\fR
.PP
.RS 4
The current playlist position.
.RE

.TP
\fBplayback_status\fR
.PP
.RS 4
The playback status as a string (Stopped, Playing, Paused, Unknown).
.RE

.TP
\fBplaytime\fR
.PP
.RS 4
The playtime of the currently playing song.
.RE

.TP
\fBduration\fR
.PP
.RS 4
The duration of the current song, as zero-padded minutes:seconds
.RE

.TP
\fBminutes\fR
.PP
.RS 4
The minutes part, zero-padded, of the current song duration.
.RE

.TP
\fBseconds\fR
.PP
.RS 4
The seconds part, zero-padded, of the current song duration.
.RE

.SH ALIASES
.PP
A list of command aliases are read from the configuration file in the section [alias]
at runtime. The syntax of
.B xmms2
aliases are somewhat similar to bash and other shells. An alias is defined by a list of semi-colon separated
commands and arguments. Parameter expansion is supported (see
.B Expansion
below).
.PP
.TP
The default configuration includes the following aliases:
.PP

.TP
\fBaddpls\fR
.PP
.RS 4
add \-f \-P $@
.RE
.PP

.TP
\fBclear\fR
.PP
.RS 4
playlist clear
.RE
.PP

.TP
\fBstatus\fR
.PP
.RS 4
current \-f $1
.RE
.PP

.TP
\fBls\fR
.PP
.RS 4
list
.RE
.PP

.TP
\fBmute\fR
.PP
.RS 4
server volume 0
.RE
.PP

.TP
\fBquit\fR
.PP
.RS 4
server shutdown
.RE
.PP

.TP
\fBrepeat\fR
.PP
.RS 4
seek 0
.RE
.PP

.TP
\fBscap\fR
.PP
.RS 4
stop ; playlist clear ; add $@ ; play
.RE
.PP

.SS Expansion
.B Positional Parameters
.RS 4
An alias can use positional parameters, for example:
.PP
foo = add \-f $1 $3
.PP
foo ctkoz.ogg and slre.ogg
.PP
Will result in:
.PP
add \-f ctkoz.ogg slre.ogg
.PP
.RE
.B Special Parameters
.RS 4
.B $@
.RS 4
This expands to all parameters passed to the alias.
.RE
.PP
.RE
.SH CONFIGURATION
.PP
All control characters are interpreted as expected, including ANSI escape sequences.
.PP
AUTO_UNIQUE_COMPLETE
.RS 4
Boolean, complete an abbreviation of a command and it's arguments. For example: `serv vol 42' will
complete to `server volume 42'. (Note: Abbreviations must be non-ambiguous)
.RE
.PP
CLASSIC_LIST
.RS 4
Boolean, format
.B list
output similar to the classic cli.
.RE
.PP
CLASSIC_LIST_FORMAT
.RS 4
String to format classic
.B list
output with.
.RE
.PP
GUESS_PLS
.RS 4
Boolean, try to guess if the URL is a playlist and add accordingly. (Not reliable)
.RE
.PP
HISTORY_FILE
.RS 4
File to save command history to.
.RE
.PP
PLAYLIST_MARKER
.RS 4
String to use to mark the current active entry in the playlist
.RE
.PP
PROMPT
.RS 4
String to use as a prompt in
.B INTERACTIVE MODE
.RE
.PP
SERVER_AUTOSTART
.RS 4
Boolean, if true xmms2 will attempt to start \fBxmms2d\fR(1) if it's not running already.
.RE
.PP
SHELL_START_MESSAGE
.RS 4
Boolean, if true,
.B xmms2
will display a greeting message and basic help when started in
.B INTERACTIVE MODE
.RE
.PP
STATUS_FORMAT
.RS 4
String to format
.B status
output with.
.RE
.SH FILES
.PP
$XDG_CACHE_HOME/xmms2/nyxmms2_history
.RS 4
Default command history file if HISTORY_FILE is unset.
.RE
.PP
$XDG_CONFIG_HOME/xmms2/clients/nycli.conf
.RS 4
The configuration file for
.B xmms2
.RE
.SH ENVIRONMENT
.PP
XMMS_PATH
.RS 4
Override the default connection path.
.TP
To connect via IPv4
tcp://IPv4-Address:port
.TP
To connect via IPv6
tcp://[IPv6-Address]:port
.TP
To connect via unix socket
unix:///path/to/socket
.RE
.SH BUGS
Please report all bugs at http://bugs.xmms2.org
.SH AUTHORS
Igor Assis, Anders Waldenborg, Anthony Garcia, Sebastien Cevey, and Jonne Lehtinen, Daniel Svensson, Raphaël Bois
.PP
See the
.B AUTHORS
file in the XMMS2 source distribution for more info.
.PP
The blame for this man page is on Anthony.
.PP
If you contributed and feel you should be listed here please send me a mail.
