# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2007 XMMS2 Team
#

from Params import g_platform

def build(bld):
    if g_platform == 'win32':
        platform_sources = "transport_win.c"
    else:
        platform_sources = "socket_unix.c transport_unix.c"

    obj = bld.create_obj('cc', 'staticlib')
    obj.source = " ".join(["msg.c", "socket_tcp.c", "transport.c",
                           "url.c", platform_sources])
    obj.includes='. ../../include'
    obj.target='xmmsipc'
    obj.install_var = 0

def configure(conf):
    pass

def set_options(opt):
    pass
