from waftools.plugin import plugin

def plugin_build(bld, obj):
    if bld.env['HAVE_FSTATAT'] and bld.env['HAVE_DIRFD']:
        obj.source.append('browse/fstatat.c')
    else:
        obj.source.append('browse/gdir.c')

def plugin_configure(conf):
    conf.check_cc(function_name='fstatat', header_name=['fcntl.h','sys/stat.h'], defines=['_ATFILE_SOURCE=1'])

    conf.check_cc(function_name='dirfd', header_name=['dirent.h','sys/types.h'])

    return True

configure, build = plugin("file", configure=plugin_configure, build=plugin_build, libs=["fstatat"])
