def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_html'
  obj.source = 'html.c'

def configure(conf):
  conf.check_message_custom('html plugin', '', 'currently broken, disabled')
