# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2013 XMMS2 Team
#

def build(bld):
    source = """
    xlist.c
    value_serialize.c
    xmmsv_bitbuffer.c
    xmmsv_build.c
    xmmsv_coll.c
    xmmsv_copy.c
    xmmsv_dict.c
    xmmsv_general.c
    xmmsv_list.c
    xmmsv_util.c
    """.split()

    bld.objects(
        features = 'visibilityhidden',
        cflags=bld.env.CFLAGS_cshlib + ['-DXMMSV_USE_INT64=1'],
        target = 'xmmstypes',
        source = source,
        includes = '. ../../.. ../../include ../../includepriv',
        install_path = None
        )


def configure(conf):
    return True


def options(opt):
    pass
