# encoding: utf-8
#
# Copyright 2006 David Anderson <dave at natulte.net>

import os

def build(bld):
    obj = bld.create_obj('cc', 'staticlib')
    obj.source = "coll.c xlist.c".split()
    obj.includes='. ../../include ../../includepriv'
    obj.target='xmmstypes'
    obj.install_in = 0

def configure(conf):
    pass

def set_options(opt):
    pass
