from waftools.plugin import plugin
from Params import g_platform

def plugin_configure(conf):
    platform_names = ['netbsd', 'openbsd']

    if not filter(lambda x: g_platform.startswith(x), platform_names):
        return False

    return True

configure, build = plugin('sun', configure=plugin_configure, output_prio=3)
