import sys

def build(bld):
  obj = bld.create_obj('cpp', 'shlib')
  obj.target = 'sun'
  obj.sources = 'sun.c'

def configure(conf):
  conf.check_message_custom('sun plugin', '', 'currently broken, disabled')
