def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_speex'
  obj.source = 'speex.c'

def configure(conf):
  conf.check_message_custom('speex plugin', '', 'currently broken, disabled')
