from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_pkg('libcurl', destvar='curl'):
        return True
    cfg = conf.create(configurator='cfgtool')
    cfg.binary = 'curl-config'
    cfg.uselib = 'curl'
    cfg.run()
    return conf.env['HAVE_curl']

configure, build = plugin('lastfmeta', configure=plugin_configure,
                          extra_libs=['curl'])
