from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cc(lib="vorbisidec", header_name="tremor/ivorbisfile.h",
                      uselib_store="tremor")

configure, build = plugin('tremor',
                          configure=plugin_configure,
                          libs=["tremor"])
