import sys

def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_oss'
  obj.source = 'oss.c'
  obj.uselib = 'ossaudio'

def configure(conf):
  conf.check_tool('checks')
  if conf.check_header2('sys/soundcard.h', mandatory=0):
    conf.check_library2('ossaudio', mandatory=0, uselib='ossaudio')
    if sys.platform in ('netbsd', 'openbsd'):
      conf.env['CCDEFINES_ossaudio'].append('DEFAULT_DEVICE="/dev/audio"')
    else:
      conf.env['CCDEFINES_ossaudio'].append('DEFAULT_DEVICE="/dev/dsp"')
