from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="libofa", uselib_store="ofa", args="--cflags --libs")

configure, build = plugin('ofa', configure=plugin_configure, libs=["ofa"])
