from os import environ;

Import('base_env')
Export('base_env')

SConscript('lib/xmmsclient/SConscript')
SConscript('lib/xmmsclient-glib/SConscript')

# breaks the build :(
# SConscript('lib/ruby/SConscript')

SConscript('cli/SConscript')

# SDL NOT YET IN NEW API
if base_env.HasGroup("sdl") and base_env.HasGroup("sdl-ttf"):
	SConscript('sdl-client/SConscript')

if base_env.HasGroup("ecore") :
	SConscript('lib/xmmsclient-ecore/SConscript')
