from os import environ;

Import('base_env')
Export('base_env')

SConscript('lib/xmmsclient/SConscript')
SConscript('lib/xmmsclient-glib/SConscript')
SConscript('lib/python/SConscript')
SConscript('cli/SConscript')

if base_env.HasGroup("qt") and environ.has_key ('QTDIR'):
# QT CLIENT NOT YET IN NEW API
#	SConscript('qt/SConscript')
	SConscript('lib/xmmsclient-qt/SConscript')
# SDL NOT YET IN NEW API
if base_env.HasGroup("sdl") and base_env.HasGroup("sdl-ttf"):
	SConscript('sdl-client/SConscript')

if base_env.HasGroup("ecore") :
	SConscript('lib/xmmsclient-ecore/SConscript')
