def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_ao'
  obj.includes = '../../include'
  obj.source = 'ao.c'
  obj.uselib = 'ao glib-2.0'

def configure(conf):
  if conf.check_pkg('ao', destvar='ao'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('ao')
