import sys

def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_wave'
  obj.includes = '../../include'
  obj.source = 'wave.c'
  obj.uselib = 'glib-2.0'

def configure(conf):
  conf.env['XMMS_PLUGINS_ENABLED'].append('wave')
