from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_pkg('libcurl', destvar='curl'):
        return True
    cfg = conf.create(configurator='cfgtool')
    cfg.binary = 'curl-config'
    cfg.uselib = 'curl'
    return (cfg.run() and conf.env['HAVE_curl'])

configure, build = plugin('curl', configure=plugin_configure,
                          source=['curl_http.c'], extra_libs=['curl', 'socket'])
