def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.includes = '../../include'
  obj.target = 'xmms_diskwrite'
  obj.source = 'diskwrite.c'
  obj.uselib = 'glib-2.0'

def configure(conf):
  conf.env['CCDEFINES'].append('_REENTRANT')
  conf.env['XMMS_PLUGINS_ENABLED'].append('diskwrite')
