from waflib import Errors
from waftools.plugin import plugin

def plugin_configure(conf):
    try:
        conf.check_cfg(package="mms", uselib_store="mms",
                args="--cflags --libs")
    except Errors.ConfigurationError:
        conf.check_cfg(package="libmms", uselib_store="mms",
                args="--cflags --libs")

configure, build = plugin("mms", configure=plugin_configure, libs=["mms"])
