def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_mms'
  obj.includes = '../../include'
  obj.source = 'mms.c'
  obj.uselib = 'mms glib-2.0'

def configure(conf):
  if (conf.check_pkg('mms', destvar='mms') or
      conf.check_pkg('libmms', destvar='mms')):
    conf.env['XMMS_PLUGINS_ENABLED'].append('mms')
