Import ('base_env')

if base_env.HasGroup ("ruby") :
	sources = Split ("rb_xmmsclient_main.c "
	                 "rb_xmmsclient.c "
	                 "rb_result.c")

	env = base_env.Copy (CPPPATH = ['../xmmsclient'],
	                     LIBPATH = ['../xmmsclient'],
	                     LIBS = ['xmmsclient'])

	env.AddFlagsFromGroup ("ruby")
	env.AddFlagsFromGroup ("glib")
	env['CPPPATH'].append ("../xmmsclient-glib")
	env['LIBPATH'].append ("../xmmsclient-glib")
	env['LIBS'].append ("-lxmmsclient-glib")

	if env.HasGroup ("ecore") :
		env.AddFlagsFromGroup ("ecore")
		env['CPPPATH'].append ("../xmmsclient-ecore")
		env['LIBPATH'].append ("../xmmsclient-ecore")
		env['LIBS'].append ("-lxmmsclient-ecore")

	env.XmmsRuby ('xmmsclient', sources)
