Import ('base_env')

if base_env.HasGroup ("ruby") :
	sources = Split ("rb_xmmsclient_main.c "
	                 "rb_xmmsclient.c "
	                 "rb_result.c")

	env = base_env.Copy (CPPPATH = ['#src/include'],
	                     LIBPATH = ['#builddir/clients/lib/xmmsclient',
	                                '#builddir/clients/lib/xmmsclient-glib'],
	                     LIBS = ['xmmsclient', 'xmmsclient-glib'])

	env.AddFlagsFromGroup ("ruby")
	env.AddFlagsFromGroup ("glib")

	if env.HasGroup ("ecore") :
		env.AddFlagsFromGroup ("ecore")
		env['LIBPATH'].append ("#builddir/clients/lib/xmmsclient-ecore")
		env['LIBS'].append ("xmmsclient-ecore")

	env.XmmsRuby ('xmmsclient', sources)
