from waftools.plugin import plugin

def plugin_configure(conf):
    return True

def plugin_build(bld, obj):
    obj.find_sources_in_dirs('. gme', excludes=['gme.c'])

configure, build = plugin('gme', needs_lib=True, configure=plugin_configure, source=[], build=plugin_build)
