from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cc(lib="m", uselib_store="math"):
        return False
    return True

configure, build = plugin("karaoke", configure=plugin_configure, libs=["math"])
