from waftools.plugin import plugin

def plugin_configure(conf):
    return conf.check_library2("m", uselib='math', mandatory=0)

configure, build = plugin('karaoke', configure=plugin_configure, extra_libs=['math'])
