def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_flac'
  obj.includes = '../../include'
  obj.source = 'flac.c'
  obj.uselib = 'flac glib-2.0'

def configure(conf):
  conf.check_tool('checks')
  if (conf.check_header2('FLAC/all.h', mandatory=0) and
      conf.check_library2('FLAC', uselib='flac', mandatory=0)):
    conf.env['XMMS_PLUGINS_ENABLED'].append('flac')
