import os
import Params

def build(bld):
    pass

def set_option(env):
    pass

def configure(conf):
    """Set the values needed by xmms_defs.h.in in the environment."""

    defs = {}

    defs['PKGLIBDIR'] = os.path.join(conf.env['PREFIX'],
                                     'lib', 'xmms2')
    defs['BINDIR']    = conf.env['BINDIR']
    defs['SHAREDDIR'] = os.path.join(conf.env['PREFIX'],
                                     'share', 'xmms2')
    defs['SCRIPTDIR'] = os.path.join(conf.env['PREFIX'],
                                     'share', 'xmms2', 'scripts', 'startup.d')

    defs['XMMS_VERSION'] = conf.env['VERSION']

    defs['XMMS_PATH_MAX'] = 255
    l = conf.env['XMMS_OUTPUT_PLUGINS']
    l.sort()
    prio,name = l[-1]
    if prio == -1:
        Params.warning("No output plugin found, this is bad")
    defs['XMMS_OUTPUT_DEFAULT'] = name
    if Params.g_platform == 'darwin':
        defs["USERCONFDIR"] = 'Library/xmms2'
        defs["USERCACHEDIR"] = 'Library/xmms2/logs'
    else:
        defs['USERCONFDIR'] = '.config/xmms2'
        defs['USERCACHEDIR'] = '.cache/xmms2'
    defs['SYSCONFDIR'] = '/etc/xmms2'

    conf.env['XMMS_DEFS'] = defs
    conf.env['PLUGINDIR'] = defs['PKGLIBDIR']

    # The plugin path in Windows should be relative, not absolute
    if Params.g_platform == 'win32':
        defs['PKGLIBDIR'] = 'Plugins/'

    for i in defs:
        conf.add_define(i, defs[i])
    conf.write_config_header('xmms_configuration.h')

    print "\nDefault output plugin: ",
    Params.pprint('BLUE', conf.env["XMMS_DEFS"]['XMMS_OUTPUT_DEFAULT'])

    return True

