/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *frame2;
  GtkWidget *fixed1;
  GtkWidget *play;
  GtkWidget *image1;
  GtkWidget *prev;
  GtkWidget *image3;
  GtkWidget *next;
  GtkWidget *image4;
  GtkWidget *playlist;
  GtkWidget *image5;
  GtkWidget *stop;
  GtkWidget *image2;
  GtkWidget *hscale1;
  GtkWidget *title;

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainwindow, "mainwindow");
  gtk_widget_set_size_request (mainwindow, 250, 45);
  gtk_window_set_title (GTK_WINDOW (mainwindow), "xmms2-gtk2");

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_container_add (GTK_CONTAINER (mainwindow), frame2);

  fixed1 = gtk_fixed_new ();
  gtk_widget_set_name (fixed1, "fixed1");
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (frame2), fixed1);

  play = gtk_button_new ();
  gtk_widget_set_name (play, "play");
  gtk_widget_show (play);
  gtk_fixed_put (GTK_FIXED (fixed1), play, 119, 0);
  gtk_widget_set_size_request (play, 24, 24);

  image1 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (play), image1);

  prev = gtk_button_new ();
  gtk_widget_set_name (prev, "prev");
  gtk_widget_show (prev);
  gtk_fixed_put (GTK_FIXED (fixed1), prev, 168, 0);
  gtk_widget_set_size_request (prev, 24, 24);

  image3 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image3, "image3");
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (prev), image3);

  next = gtk_button_new ();
  gtk_widget_set_name (next, "next");
  gtk_widget_show (next);
  gtk_fixed_put (GTK_FIXED (fixed1), next, 192, 0);
  gtk_widget_set_size_request (next, 24, 24);

  image4 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (next), image4);

  playlist = gtk_button_new ();
  gtk_widget_set_name (playlist, "playlist");
  gtk_widget_show (playlist);
  gtk_fixed_put (GTK_FIXED (fixed1), playlist, 216, 0);
  gtk_widget_set_size_request (playlist, 24, 24);

  image5 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (playlist), image5);

  stop = gtk_button_new ();
  gtk_widget_set_name (stop, "stop");
  gtk_widget_show (stop);
  gtk_fixed_put (GTK_FIXED (fixed1), stop, 144, 0);
  gtk_widget_set_size_request (stop, 24, 24);

  image2 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (stop), image2);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 1, 0, 0)));
  gtk_widget_set_name (hscale1, "hscale1");
  gtk_widget_show (hscale1);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale1, 0, 0);
  gtk_widget_set_size_request (hscale1, 120, 24);
  gtk_scale_set_draw_value (GTK_SCALE (hscale1), FALSE);
  gtk_range_set_update_policy (GTK_RANGE (hscale1), GTK_UPDATE_DISCONTINUOUS);

  title = gtk_label_new ("xmms2 - it really whips the GNUs ass");
  gtk_widget_set_name (title, "title");
  gtk_widget_show (title);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), title);
  gtk_label_set_justify (GTK_LABEL (title), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) mainwindow, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) play, "clicked",
                    G_CALLBACK (on_play_clicked),
                    NULL);
  g_signal_connect ((gpointer) prev, "clicked",
                    G_CALLBACK (on_prev_clicked),
                    NULL);
  g_signal_connect ((gpointer) next, "clicked",
                    G_CALLBACK (on_next_clicked),
                    NULL);
  g_signal_connect ((gpointer) playlist, "clicked",
                    G_CALLBACK (on_playlist_clicked),
                    NULL);
  g_signal_connect ((gpointer) stop, "clicked",
                    G_CALLBACK (on_stop_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (mainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mainwindow, play, "play");
  GLADE_HOOKUP_OBJECT (mainwindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (mainwindow, prev, "prev");
  GLADE_HOOKUP_OBJECT (mainwindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (mainwindow, next, "next");
  GLADE_HOOKUP_OBJECT (mainwindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainwindow, playlist, "playlist");
  GLADE_HOOKUP_OBJECT (mainwindow, image5, "image5");
  GLADE_HOOKUP_OBJECT (mainwindow, stop, "stop");
  GLADE_HOOKUP_OBJECT (mainwindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (mainwindow, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (mainwindow, title, "title");

  gtk_widget_grab_focus (hscale1);
  return mainwindow;
}

GtkWidget*
create_playlist (void)
{
  GtkWidget *playlist;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label1;
  GtkWidget *fixed2;
  GtkWidget *Add;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image6;
  GtkWidget *label3;
  GtkWidget *shuffle;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image7;
  GtkWidget *label4;
  GtkWidget *delete;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image8;
  GtkWidget *label5;
  GtkWidget *clear;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image9;
  GtkWidget *label6;

  playlist = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (playlist, "playlist");
  gtk_widget_set_size_request (playlist, 300, 500);
  gtk_window_set_title (GTK_WINDOW (playlist), "xmms2 playlist");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (playlist), vbox1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview1, "treeview1");
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  label1 = gtk_label_new ("Playlist");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  fixed2 = gtk_fixed_new ();
  gtk_widget_set_name (fixed2, "fixed2");
  gtk_widget_show (fixed2);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed2, FALSE, TRUE, 0);
  gtk_widget_set_size_request (fixed2, 197, 30);

  Add = gtk_button_new ();
  gtk_widget_set_name (Add, "Add");
  gtk_widget_show (Add);
  gtk_fixed_put (GTK_FIXED (fixed2), Add, 0, 0);
  gtk_widget_set_size_request (Add, 72, 24);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Add), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image6, "image6");
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox1), image6, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic ("Add");
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  shuffle = gtk_button_new ();
  gtk_widget_set_name (shuffle, "shuffle");
  gtk_widget_show (shuffle);
  gtk_fixed_put (GTK_FIXED (fixed2), shuffle, 216, 0);
  gtk_widget_set_size_request (shuffle, 72, 24);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (shuffle), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image7, "image7");
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox2), image7, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic ("Shuffle");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  delete = gtk_button_new ();
  gtk_widget_set_name (delete, "delete");
  gtk_widget_show (delete);
  gtk_fixed_put (GTK_FIXED (fixed2), delete, 72, 0);
  gtk_widget_set_size_request (delete, 72, 24);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (delete), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image8 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image8, "image8");
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox3), image8, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic ("Delete");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  clear = gtk_button_new ();
  gtk_widget_set_name (clear, "clear");
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed2), clear, 144, 0);
  gtk_widget_set_size_request (clear, 72, 24);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (clear), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image9 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image9, "image9");
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox4), image9, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic ("Clear");
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) playlist, "destroy",
                    G_CALLBACK (on_playlist_destroy),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_playlist_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Add, "clicked",
                    G_CALLBACK (on_playlist_Add_clicked),
                    NULL);
  g_signal_connect ((gpointer) shuffle, "clicked",
                    G_CALLBACK (on_shuffle_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete, "clicked",
                    G_CALLBACK (on_playlist_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_playlist_clear_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (playlist, playlist, "playlist");
  GLADE_HOOKUP_OBJECT (playlist, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (playlist, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (playlist, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (playlist, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (playlist, label1, "label1");
  GLADE_HOOKUP_OBJECT (playlist, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (playlist, Add, "Add");
  GLADE_HOOKUP_OBJECT (playlist, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (playlist, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (playlist, image6, "image6");
  GLADE_HOOKUP_OBJECT (playlist, label3, "label3");
  GLADE_HOOKUP_OBJECT (playlist, shuffle, "shuffle");
  GLADE_HOOKUP_OBJECT (playlist, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (playlist, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (playlist, image7, "image7");
  GLADE_HOOKUP_OBJECT (playlist, label4, "label4");
  GLADE_HOOKUP_OBJECT (playlist, delete, "delete");
  GLADE_HOOKUP_OBJECT (playlist, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (playlist, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (playlist, image8, "image8");
  GLADE_HOOKUP_OBJECT (playlist, label5, "label5");
  GLADE_HOOKUP_OBJECT (playlist, clear, "clear");
  GLADE_HOOKUP_OBJECT (playlist, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (playlist, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (playlist, image9, "image9");
  GLADE_HOOKUP_OBJECT (playlist, label6, "label6");

  return playlist;
}

