#gtk2 client

Import('base_env')

xmms2_sources = Split ("interface.c support.c callbacks.c main.c")

env = base_env.Copy(CPPPATH = ['../../lib/xmmsclient','../../..'],
	LIBPATH = ["../../lib/xmmsclient/"],
	LIBS = ["xmmsclient"])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("gtk2")

env.XmmsProgram("xmms2-gtk2", xmms2_sources)
