from waftools import tool
import sys

def build(bld):
    obj = bld(features = 'c cshlib',
        target = 'xmmsclient-cf',
        includes = '../../../.. ../../../include',
        source = 'xmmsclient-cf.c',
        use = 'xmmsclient CoreFoundation',
        vnum = '1.0.0'
        )
    tool.add_install_flag(bld, obj)

def configure(conf):
    if sys.platform != 'darwin':
        conf.fatal("Not supported on this platform")

    conf.env.FRAMEWORK_CoreFoundation = ['CoreFoundation']
    return True

def options(opt):
    pass
