import Params

def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.target = 'xmms2-launcher'
    obj.source = ['xmms2-launcher.c']
    obj.includes = '../../include'
    obj.uselib = 'glib2'
    obj.uselib_local = 'xmmsutils'

    obj = bld.create_obj('man')
    obj.files = ['xmms2-launcher.1']

def configure(conf):
    if Params.g_platform == 'win32':
        return False
    return True

def set_options(opt):
    pass
