.\" 
.\" XMMS2 - The next generation of the XMMS music player.
.\"
.\" xmms2-launcher.1 - xmms2-launcher man page
.\"
.\" Copyright (C) 2005-2009 XMMS2 Team
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.TH XMMS2-LAUNCHER 1
.SH NAME
xmms2-launcher \- XMMS2 daemon launcher
.SH SYNOPSIS
.P
.I xmms2-launcher
[
.B -?
/ 
.B --help
]
.P
.I xmms2-launcher
[
.B -l 
logfile / 
.B --logfile=
logfile]
[
.B -P 
pidfile / 
.B --pidfile=
pidfile]
.SH DESCRIPTION

.B XMMS2
is a redesign of the XMMS (http://www.xmms.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organise your music.
.PP

.I xmms2-launcher
starts 
.I xmms2d(1)
in the background. The main feature is that it does not exit until the IPC system of 
.B XMMS2
is available, meaning that as soon as the 
.I xmms2-launcher
process has exited successfully 
.I xmms2d(1)
is ready to accept commands.
.PP
.I xmms2-launcher
includes command line options to change the way in which the daemon is invoked.
.TP
.BR
These options are currently recognised:
.TP
.I
-l logfile / --logfile=logfile
Write log file to 
.I logfile
instead of the default log file location
.TP
.I
- P pidfile / --pidfile=pidfile
Write the pid of 
.I xmms2d
to the file specified by 
.I pidfile
.TP
.I
-? / --help  
Show help options
.SH FILES
.TP
.I $XDG_CACHE_HOME/xmms2/xmms2d.log
The default location for a file where the log output of 
.I xmms2d(1)
is redirected. Usually ~/.cache/xmms2/xmms2d.log.
.SH SEE ALSO
xmms2d(1), http://xmms2.xmms.org
.SH HISTORY
The 
.B XMMS2
Project was started by Tobias Rundström and Anders Gustafsson. It is developed with their lead by a small group of contributers from all over the world.
.SH AUTHOR
This manual page was written by Alexander Botero-Lowry <alex@foxybanana.com>
