.\"
.\" XMMS2 - The next generation of the XMMS music player.
.\"
.\" xmms2-launcher.1 - xmms2-launcher man page
.\"
.\" Copyright (C) 2005-2012 XMMS2 Team
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH XMMS2-LAUNCHER 1
.SH NAME
xmms2-launcher \- XMMS2 daemon launcher
.SH SYNOPSIS
.B xmms2-launcher
.RB [\| -l
.IR file \|]
.RB [\| -P
.IR file \|]
.RB [\| -v \|]
.RB [\| -- \|]
.RI [\| XMMS2D_OPTION \|]
.R \|...
.br
.B xmms2-launcher -h
.SH DESCRIPTION
XMMS2 is a redesign of the XMMS (http://legacy.xmms2.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organise your music.
.PP
.B xmms2-launcher
starts
.BR xmms2d (1)
in the background. The main feature is that it does not exit until the IPC system of XMMS2 is available, meaning that as soon as the
.B xmms2-launcher
process has exited successfully
.BR xmms2d (1)
is ready to accept commands.
.SH OPTIONS
Unrecognized options and options occuring beyond pseudo-option
.B --
are passed to
.BR xmms2d (1).
.TP
.BI \-l\  file ,\ \-\-logfile= file
Write log to
.I file
instead of the default log file location.
.TP
.BI \-P\  file ,\ \-\-pidfile= file
Write the pid of
.BR xmms2d (1)
to
.IR file .
.TP
.B \-v, \-\-verbose
Make xmms2-launcher verbose.
.TP
.B \-?, \-h, \-\-help
Show short help information and exit.
.TP
.B --
Options beyond this marker are passed to
.BR xmms2d (1).
.TP
.I XMMS2D_OPTION
See
.BR xmms2d (1)
for a list of options and their effect.
.SH FILES
Below
.I CACHEDIR
is
.I $XDG_CACHE_HOME/xmms2
on UNIX if the
.BR XDG_CACHE_HOME -environment
variable is set. Otherwise it is
.I $HOME/.cache/xmms2
(UNIX except Darwin), or
.I $HOME/Library/xmms2/logs
(Darwin).
.TP
.I CACHEDIR/xmms2d.log
The default location for storing log output of
.BR xmms2d (1).
.SH ENVIRONMENT
.TP
.B XDG_CACHE_HOME
The location where the XMMS2 logs are located by default.
.SH SEE ALSO
.BR xmms2d (1),\  http://xmms2.org/ .
.SH HISTORY
The XMMS2 Project was started by Tobias Rundström and Anders Waldenborg. It is developed by a small group of contributers from all over the world.
.SH AUTHOR
This manual page was written by Alexander Botero-Lowry <alex@foxybanana.com>. It was reformatted by Erik Massop <e.massop@hccnet.nl>.
