def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_replaygain'
  obj.includes = '../../include'
  obj.source = 'replaygain.c'
  obj.uselib = 'glib-2.0'

def configure(conf):
  if conf.check_pkg('glib-2.0', vnum='2.6.0', destvar='glib-2.0'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('replaygain')
