def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_replaygain'
  obj.includes = '../../include'
  obj.source = 'replaygain.c'
  obj.uselib = 'glib-2.0'

def configure(conf):
  conf.env['XMMS_PLUGINS_ENABLED'].append('replaygain')
