from xmmsenv.plugin import plugin

def plugin_configure(conf):
  return conf.check_pkg('gnome-vfs-2.0', destvar='gnomevfs')

configure, build = plugin('gnomevfs', configure=plugin_configure,
                          needs_lib=True)
