def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_gnomevfs'
  obj.source = 'gnomevfs.c'
  obj.uselib = 'gnomevfs'

def configure(conf):
  if conf.check_pkg('gnome-vfs-2.0', destvar='gnomevfs'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('gnomevfs')
