from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_cfg(package="gio-2.0", args="--cflags --libs", uselib_store="gvfs"):
        return True
    return False

configure, build = plugin("gvfs", configure=plugin_configure, libs=["gvfs"])
