from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="gio-2.0", uselib_store="gvfs",
            args="--cflags --libs")

configure, build = plugin("gvfs", configure=plugin_configure, libs=["gvfs"])
