# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2007 XMMS2 Team
#

import os

def build(bld):
    platform_src = {'nt':'win32', 'posix':'unix'}

    obj = bld.create_obj('cc', 'staticlib')
    obj.source = "strlist.c utils_%s.c" % platform_src[os.name]
    obj.includes='. ../../include'
    obj.target='xmmsutils'
    obj.install_var = 0

def configure(conf):
    pass

def set_options(opt):
    pass
