
from xmmsapi import OBJECT_CMD_ARG_NONE
from xmmsapi import OBJECT_CMD_ARG_UINT32
from xmmsapi import OBJECT_CMD_ARG_INT32
from xmmsapi import OBJECT_CMD_ARG_STRING
from xmmsapi import OBJECT_CMD_ARG_DICT
from xmmsapi import OBJECT_CMD_ARG_LIST
from xmmsapi import OBJECT_CMD_ARG_BIN
from xmmsapi import OBJECT_CMD_ARG_COLL
from xmmsapi import PLAYBACK_STATUS_STOP
from xmmsapi import PLAYBACK_STATUS_PLAY
from xmmsapi import PLAYBACK_STATUS_PAUSE

from xmmsapi import PLAYLIST_CHANGED_ADD
from xmmsapi import PLAYLIST_CHANGED_INSERT
from xmmsapi import PLAYLIST_CHANGED_SHUFFLE
from xmmsapi import PLAYLIST_CHANGED_REMOVE
from xmmsapi import PLAYLIST_CHANGED_CLEAR
from xmmsapi import PLAYLIST_CHANGED_MOVE
from xmmsapi import PLAYLIST_CHANGED_SORT
from xmmsapi import PLAYLIST_CHANGED_UPDATE

from xmmsapi import PLUGIN_TYPE_ALL
from xmmsapi import PLUGIN_TYPE_XFORM
from xmmsapi import PLUGIN_TYPE_OUTPUT
from xmmsapi import PLUGIN_TYPE_PLAYLIST
from xmmsapi import PLUGIN_TYPE_EFFECT
