#clientlib

Import('base_env')

xmmsc_sources = Split ("xmmsclient-ecore.c")

env = base_env.Copy(CPPPATH = ['../xmmsclient', '#src/include'],
		    LIBPATH = ['../xmmsclient'],
		    LIBS = ['xmmsclient'])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("ecore")

env.XmmsLibrary('xmmsclient-ecore', xmmsc_sources)

