from waftools import tool

def build(bld):
    obj = bld.create_obj('cc', 'shlib')
    obj.target = 'xmmsclient-ecore'
    obj.includes = '../../../include'
    obj.source = 'xmmsclient-ecore.c'
    obj.uselib = 'ecore'
    obj.uselib_local = 'xmmsclient'
    obj.vnum = '1.0.0'
    tool.add_install_flag(obj)

def configure(conf):
    cfg = conf.create(configurator='cfgtool')
    cfg.binary = 'ecore-config'
    cfg.uselib = 'ecore'
    cfg.tests = {'--cflags': 'CCFLAGS', '--libs-core': 'LINKFLAGS'}

    return cfg.run()

def set_options(opt):
    pass
