#cli client

Import('base_env')

env = base_env.Copy(CPPPATH = ['../lib/xmmsclient','../..'],
	LIBPATH = ["../lib/xmmsclient/"],
	LIBS = ["xmmsclient"])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("sdl")
env.AddFlagsFromGroup("sdl-ttf")

env.Program(target = "sdl-vis" , source = ['sdl-vis.c'] )

env.Install("/usr/local/bin", "sdl-vis")
