def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_musepack'
  obj.sources = ['musepack.c', 'ape.c']
  obj.uselib = 'musepack'

def configure(conf):
  conf.check_tool('checks')
  if conf.check_library2('mpcdec', uselib='musepack', mandatory=0):
    conf.env['XMMS_PLUGINS_ENABLED'].append('musepack')
