def build(bld):
  obj = bld.create_obj('cc', 'plugin')
  obj.target = 'xmms_lastfm'
  obj.includes = '../../include'
  obj.source = 'lastfm.c'
  obj.uselib = 'curl glib-2.0'

def configure(conf):
  cfg = conf.create(configurator='cfgtool')
  cfg.binary = 'curl-config'
  cfg.uselib = 'curl'
  if cfg.run() and conf.env['HAVE_curl']:
    conf.env['XMMS_PLUGINS_ENABLED'].append('lastfm')
