def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_lastfm'
  obj.includes = '../../include'
  obj.source = 'lastfm.c'
  obj.uselib = 'curl glib-2.0'

def configure(conf):
  cfg = conf.create(configurator='cfgtool')
  cfg.binary = 'curl-config'
  cfg.uselib = 'curl'
  if (conf.check_pkg('glib-2.0', vnum='2.6.0', destvar='glib-2.0') and
      cfg.run() and conf.env['HAVE_curl']):
    conf.env['XMMS_PLUGINS_ENABLED'].append('lastfm')
