#clientlib

Import('base_env')

xmmsc_sources = "xmmsclient-carbon.c"

env = base_env.Copy(INCLUDES=["include"], LIBS=["xmmsipc", "xmmsutil", "xmmsclient"],
		    LIBPATH=["#builddir/lib/xmmsutil", "#builddir/lib/xmmsipc",
					 "#builddir/clients/lib/xmmsclient"])


env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("Carbon")

env.XmmsLibrary('xmmsclient-carbon', xmmsc_sources)

