def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_id3v2'
  obj.includes = '../../include'
  obj.source = ['id3v2plugin.c', 'id3.c']
  obj.uselib = 'glib-2.0'

def configure(conf):
  if conf.check_pkg('glib-2.0', vnum='2.6.0', destvar='glib-2.0'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('id3v2')
