from waftools.plugin import plugin

source = """
eq.c
iir.c
iir_cfs.c
iir_fpu.c
""".split()

def plugin_configure(conf):
    conf.check_cc(lib="m", uselib_store="math")

configure, build = plugin("equalizer", configure=plugin_configure, libs=["math"],
                          source=source)
