import sys
from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_header2('math.h'):
        return False
    if not conf.check_library2('m', uselib='m'):
        return False
    return True

if sys.platform == 'darwin':
    configure, build = plugin('equalizer', configure=plugin_configure,
                              extra_libs=['m'], broken=True)
else:
    configure, build = plugin('equalizer', configure=plugin_configure, extra_libs=['m'],
                              source="""eq.c iir.c iir_cfs.c iir_fpu.c""".split())
