def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_jack'
  obj.includes = '../../include'
  obj.source = 'jack.c'
  obj.uselib = 'jack glib-2.0'

def configure(conf):
  if conf.check_pkg('jack', destvar='jack'):
    conf.env['XMMS_PLUGINS_ENABLED'].append('jack')
