#cli client

Import('base_env')

env = base_env.Copy(CPPPATH = ['../lib/xmmsclient','#src/include'],
	LIBPATH = ["../lib/xmmsclient/"],
	LIBS = ["xmmsclient"])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("sdl")
env.AddFlagsFromGroup("sdl-ttf")

env.XmmsProgram("sdl-client", ['sdl-client.c'])

