#cli client

Import('base_env')

env = base_env.Copy(CPPPATH = ['../lib/xmmsclient','../lib/xmmsclient-glib','#src/include'],
	LIBPATH = ["../lib/xmmsclient/", "../lib/xmmsclient-glib"],
	LIBS = ["xmmsclient", "xmmsclient-glib"])

env.AddFlagsFromGroup("glib")
env.AddFlagsFromGroup("sdl")
env.AddFlagsFromGroup("sdl-ttf")

env.XmmsProgram("sdl-client", ['sdl-client.c'])

