from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.env["HAVE_CXX"]:
        return False
    cfg = conf.create(configurator='pkgconfig')
    cfg.name = 'libsidplay2'
    cfg.uselib = 'sidplay'
    cfg.variables = ['builders']
    if not cfg.run():
        return False

    builders = conf.env['sidplay_BUILDERS']
    conf.env['LIBPATH_sidplay'].append("%s" % builders)
    conf.env['LINKFLAGS_sidplay'].append("-rpath=%s" % builders)
    return True

def plugin_build(bld):
    obj = bld.create_obj('cpp', 'objects')
    obj.target = 'xmms_sid_cpp'
    obj.includes = '../../include'
    obj.source = """sidplay_wrapper.cpp md5.cpp""".split()
    obj.uselib = 'sidplay glib2'

    obj = bld.create_obj('cc', 'plugin')
    obj.target = 'xmms_sid'
    obj.includes = '../../include'
    obj.source = 'sid.c'
    obj.add_objects = 'xmms_sid_cpp'
    obj.uselib = 'sidplay glib2'

configure, build = plugin('sid', configure=plugin_configure,
                          build_replace=plugin_build)
