def build(bld):
  obj = bld.create_obj('cpp', 'shlib')
  obj.target = 'xmms_sid'
  obj.sources = ['sid.c', 'sidplay_wrapper.cpp', 'md5.cpp']
  obj.uselib = 'sidplay'

def configure(conf):
  conf.check_tool('checks g++')
  cfg = conf.create(configurator='pkgconfig')
  cfg.name = 'libsidplay2'
  cfg.uselib = 'sidplay'
  cfg.variables = ['builders']
  if cfg.run():
    builders = conf.env['sidplay_BUILDERS']
    conf.env['LIBPATH_sidplay'].append("%s" % builders)
    conf.env['LINKFLAGS_sidplay'].append("-rpath=%s" % builders)
    conf.env['XMMS_PLUGINS_ENABLED'].append('sid')
