def build(bld):
    obj = bld.create_obj('cc', 'program')
    obj.target = 'vistest'
    obj.source = """vistest.c""".split()
    obj.includes = '. ../../include'
    obj.uselib_local = 'xmmsclient-glib xmmsclient'
    obj.uselib = 'glib2'

def configure(conf):
    return True

def set_options(opt):
    pass
