MODULE += CORE

# this could probably be removed in some nice way?
CORE_DIR=src/xmms
CORE_OBJS=	config.o \
		plugin.o \
		object.o \
		ringbuf.o \
		transport.o \
		decoder.o \
		output.o \
		playlist.o \
		magic.o \
		plsplugins.o \
		dbus.o \
		unixsignal.o \
		log.o \
		util.o \
		visualisation.o \
		main.o \
		mediainfo.o \
		effect.o \
		playlist_entry.o \
		error.o \
		sqlite.o \
		medialib.o

CORE_PROGRAM=xmms2d
CORE_DEPENDS=DBUS GLIB MATH SQLITE
