#!/usr/bin/env python
# encoding: utf-8
#
# Copyright 2006 David Anderson <dave at natulte.net>

def build(bld):
  pass

def configure(conf):
  conf.check_pkg('glib-2.0', destvar='GLIB', vnum='2.6.0')
  conf.check_pkg('gmodule-2.0', destvar='GMODULE', vnum='2.6.0')
  conf.check_pkg('gthread-2.0', destvar='GTHREAD', vnum='2.6.0')
  conf.check_pkg('sqlite3', destvar='SQLITE3')

def set_options(opt):
  pass
