.\"
.\" XMMS2 - The next generation of the XMMS music player.
.\"
.\" xmms2d.1 - xmms2d (xmms2 daemon) man page
.\"
.\" Copyright (C) 2005-2017 XMMS2 Team
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH XMMS2D 1
.SH NAME
xmms2d \- XMMS2 daemon which handles the playback of music and storage of music metadata
.SH SYNOPSIS
.B xmms2d
.RB [\| \-v \||\| \-q \|]
.RB [\| \-p
.IR dir \|]
.RB [\| \-o
.IR plugin \|]
.RB [\| \-i
.IR url \|]
.RB [\| -c
.IR file \|]
.RB [\| -s
.IR fd \|]
.RB [\| --yes-run-as-root \|]
.br
.B xmms2d -?
.br
.B xmms2d -V
.SH DESCRIPTION
XMMS2 is a redesign of the XMMS (http://legacy.xmms2.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organise your music.
.PP
.B xmms2d
is the daemon through which XMMS2 clients playback and manage music. A client library provided allows third parties to easily write XMMS2 clients, especially using the Python and Ruby bindings.
.PP
.B xmms2d
uses a three part method to playback music. Music is accessed from disk or network using a transport plugin, the data is then passed on to a decoder plugin which decodes the audio into a form that can be played back by an output plugin. 
.SH OPTIONS
.SS General options
.TP
.B \-v, \-\-verbose
Increase verbosity.
.TP
.B \-q, \-\-quiet
Decrease verbosity.
.TP
.BI \-p\  dir ,\ \-\-plugindir= dir
Use plugin directory
.IR dir .
.TP
.BI \-o\  plugin ,\ \-\-output= plugin
Use output plugin
.IR plugin .
.TP
.BI \-i\  url ,\ --ipc-socket= url
Listen to socket at
.IR url .
Multiple sockets can be specified separated by
.BR ; -characters.
See section
.BR IPC\ SOCKET .
.TP
.BI \-c\  file ,\ \-\-conf= file
Use configuration file
.IR file .
.TP
.BI \-s\  fd ,\ \-\-status-fd= fd
Write to filedescriptor
.I fd
when started. This can be used to wait until inter-process communication (IPC) is up, as for instance
.BR xmms2-launcher (1)
does.
.TP
.B \-\-yes\-run\-as\-root
Allow
.B xmms2d
to be run as root.
.SS Getting help
.TP
.B \-h, \-?, \-\-help
Display basic help information and exit.
.TP
.B \-V, \-\-version
Display version information.
.SH "IPC SOCKET"
XMMS2 clients use IPC sockets to communicate with
.BR xmms2d .
These IPC sockets are specified in an URL based format with three possible transport methods: unix, tcp, and tcp6.
.PP
The TCP methods allow clients to connect over IPv4 and IPv6 to
.B xmms2d
and therefore allow remote control of XMMS2. A typical IPC socket url using TCP is
.IR tcp://127.0.0.1:9667 .
.PP
The UNIX transport method is for local clients only and creates a file through which XMMS2 clients can access
.BR xmms2d .
A typical IPC socket path using the UNIX transport is
.IR unix:///tmp/xmms-ipc-foobar .
.SH FILES
Below
.I CONFDIR
is
.I $XDG_CONFIG_HOME/xmms2
on UNIX if the
.BR XDG_CONFIG_HOME -environment
variable is set. Otherwise it is
.I $HOME/.config/xmms2
(UNIX except Darwin), or
.I $HOME/Library/xmms2
(Darwin).
On Win32 it is
.IR %APPDATA%/xmms2 .
.TP
.IR CONFDIR/xmms2.conf
An XML formatted configuration file that allows changing the settings of
.BR xmms2d .
.TP
.IR CONFDIR/startup.d/
A directory populated with programs that are run when
.B xmms2d
is executed.
An alternative location can be specified in the configuration file.
.TP
.IR CONFDIR/shutdown.d/
A directory populated with programs that are run when
.B xmms2d
is shutdown correctly.
An alternative location can be specified in the configuration file.
.TP
.IR CONFDIR/medialib.db
An
.BR sqlite3 (1)
database that includes information about each song that has been added the the XMMS2 media library.
An alternative location can be specified in the configuration file.
.TP
.IR CONFDIR/bindata/
A directory that contains files with binary data entrusted to the XMMS2 media library, such as cover art.
An alternative location can be specified in the configuration file.
.TP
.I /tmp/xmms-ipc-USER
The typical location for the UNIX IPC Socket. Here
.I USER
is the name of the user that executed
.BR xmms2d .
.SH ENVIRONMENT
.TP
.B XDG_CONFIG_HOME
The path where the XMMS2 configuration files and resources are located.
.TP
.B XMMS_PATH
The url of the first socket that
.B xmms2d
listens to. This environment variable is set for programs in the startup and shutdown directories.
.TP
.B XMMS_PATH_FULL
A
.BR ; -separated
list of paths to which
.B xmms2d
listens. This environment variable is set for programs in the startup and shutdown directories.
.SH SEE ALSO
.BR xmms2 (1),\  xmms2-launcher (1),\  http://xmms2.org/ .
.SH HISTORY
The XMMS2 Project was started by Tobias Rundström and Anders Waldenborg. It is developed by a small group of contributers from all over the world.
.SH AUTHOR
This manual page was originally written by Alexander Botero-Lowry <alex@foxybanana.com>. It was reformatted and slightly extended by Erik Massop <e.massop@hccnet.nl>.
