.\" 
.\" XMMS2 - The next generation of the XMMS music player.
.\"
.\" xmms2d.1 - xmms2d (xmms2 daemon) man page
.\"
.\" Copyright (C) 2005-2009 XMMS2 Team
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer
.\"    in this position and unchanged.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.TH XMMS2D 1
.SH NAME
xmms2d \- XMMS2 daemon which handles the playback of music and storage of music metadata
.SH SYNOPSIS
.I xmms2d
[
.B -vqn
] [
.B -? / --help
] [
.B -V / --version
] [
.B -p
plugin_path /
.B --plugindir=
plugin_path
] [
.B -o
output_plugin /
.B --output=
output_plugin
] [
.B -c 
path_to_config_file /
.B --conf=
path_to_config_file
] [
.B -s 
fd /
.B --status-fd=
fd
]
.SH DESCRIPTION
.B XMMS2 
is a redesign of the XMMS (http://www.xmms.org) music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plugins. On top of this, there is a flexible media library to organise your music.
.PP
.I xmms2d
is the daemon through which 
.B XMMS2
clients playback and manage music. A client library provided allows third parties to easily write
.B XMMS2
clients, especially using the Python and Ruby bindings.
.PP
.I xmms2d
uses a three part method to playback music. Music is accessed from disk or network using a transport plugin, the data is then passed on to a decoder plugin which decodes the audio into a form that can be played back by an output plugin.  
.PP
.I xmms2d 
includes command line options to change the way in which the daemon functions. 
.TP
.BR
These options are currently recognised: 
.TP
.I -v 
Increases the vebosity of
.I xmms2d
.TP
.I -q
Decrease the verbosity of
.I xmms2d
.TP
.I -V | --version 
Returns the 
.B XMMS2
version
.TP
.I -? | --help
Displays basic help information for
.I xmms2d
.TP
.I -n | --no-logging
Disables logging
.TP
.I -o output_plugin | --output=output_plugin
Specifies a different output plugin to use in place of the default
.TP
.I -p plugin_path | --plugindir=plugin_path
Specifies a different plugin directory path than the default
.TP
.I -c path_to_config_file | --conf=path_to_config_file
Specifies a path to an alternative configuration file
.TP
.I -s fd | --status-fd=fd
Specifies a file descriptor to write to when started
.SH "IPC SOCKET"
.B XMMS2
clients uses IPC sockets to communicate with
.I xmms2d. 
These IPC sockets are specified in a URL based format with three possible transport methods: unix, tcp, and tcp6. 
.PP
The TCP methods allow clients to connect over IPv4 and IPv6 to 
.I xmms2d
and therefore allow remote control of 
.B XMMS2.
.TP
A typical IPC socket path using TCP would be: 
.B tcp://127.0.0.1:9667 
.PP
The UNIX transport method is for local clients only and creates a file through which 
.B XMMS2
clients can access 
.I xmms2d.
.TP
A typical IPC socket path using the UNIX transport would be:
.B unix:///tmp/xmms-ipc-foobar 
.SH FILES
.TP
.I $HOME/.config/xmms2/medialib.db or $XDG_CONFIG_HOME/xmms2/medialib.db
An sqlite3 database that includes information about each song that has been added to the 
.B XMMS2
media library
.TP
.I $HOME/.config/xmms2/xmms2.conf or $XDG_CONFIG_HOME/xmms2/xmms2.conf
An XML formatted configuration file that allows you to change the default settings of
.I xmms2d
.TP
.I $HOME/.config/xmms2/startup.d or $XDG_CONFIG_HOME/xmms2/startup.d
A directory populated with programs that run when 
.I xmms2d
is executed
.TP
.I $HOME/.config/xmms2/shutdown.d or $XDG_CONFIG_HOME/xmms2/shutdown.d
A directory populated with programs that run when
.I xmms2d
is shutdown correctly
.TP
.I /tmp/xmms-ipc-USER
The typical location for the UNIX IPC Socket. USER is the name of the user that executed 
.I xmms2d.
.SH ENVIRONMENTAL VARIABLES
.TP
.I XDG_CONFIG_HOME
The path where the xmms2 configuration files and resources are located
.SH SEE ALSO
xmms2(1), xmms2-launcher(1), http://xmms2.xmms.org
.SH HISTORY
The
.B XMMS2
Project was started by Tobias Rundström and Anders Gustafsson. It is developed with their lead by a small group of contributers from all over the world.
.SH AUTHOR
This manual page was written by Alexander Botero-Lowry <alex@foxybanana.com>
