from waftools.plugin import plugin

def plugin_configure(conf):
    return (conf.check_pkg('libcdio_cdda', destvar='cdda') and
            conf.check_pkg('libdiscid', destvar='discid'))

configure, build = plugin('cdda', configure=plugin_configure,
                          extra_libs=['discid'], needs_lib=True)
