from xmmsenv.plugin import plugin

def plugin_configure(conf):
  cfg = conf.create(configurator='cfgtool')
  cfg.binary = 'ffmpeg-config'
  cfg.uselib = 'wma'
  cfg.tests = {'--cflags': 'CCFLAGS',
               '--plugin-libs': 'LINKFLAGS'}
  return (cfg.run() or conf.check_pkg('libavformat', destvar='wma'))

configure, build = plugin('wma', configure=plugin_configure, needs_lib=True)
