def build(bld):
  obj = bld.create_obj('cc', 'shlib')
  obj.target = 'xmms_pls'
  obj.source = 'pls.c'

def configure(conf):
  conf.check_message_custom('pls plugin', '', 'currently broken, disabled')
