import os

def build(bld):
    paths = ['xmms', 'xmmsc', 'xmmsclient', 'xmmsclient/xmmsclient++']
    for p in paths:
        bld.add_subdirs(p)
        f = [os.path.join(p, a) for a in os.listdir(os.path.join('src','include',p)) if a.endswith('.h')]
        bld.install_files(os.path.join(bld.env.INCLUDEDIR, 'xmms2', p), " ".join(f))

def configure(conf):
    conf.sub_config("xmms")

    return True

def set_options(env):
    pass
