import os

def build(bld):
    # FIXME: This is a test that should work.
    for d in bld.path.ant_glob('**', dir=True, src=False):
        rpath = d.path_from(bld.path)
        bld.recurse(rpath)
        f = d.ant_glob('*.h')
        if f:
            bld.install_files(os.path.join(bld.env.INCLUDEDIR, 'xmms2', rpath), f)

def configure(conf):
    conf.recurse("xmms")

    return True

def options(env):
    pass
