from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="sndfile", uselib_store="sndfile",
            args="--cflags --libs")

configure, build = plugin("sndfile", configure=plugin_configure,
                          libs=["sndfile"])

