from waftools.plugin import plugin

def plugin_configure(conf):
    if conf.check_cfg(package="sndfile", uselib_store="sndfile", args="--cflags --libs"):
        return True
    return False

configure, build = plugin("sndfile", configure=plugin_configure,
                          libs=["sndfile"])

